# Importing Libraries


In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [9]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,-2:]],axis = 1)

new_df = new_df[new_df['City'] == 'Bengaluru']

In [10]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [11]:
new_df['Year'] = new_df['Date'].dt.year

In [12]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [13]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [14]:
ds_delhi_15

City       Date    AQI    AQI_Bucket
Year                                           
2015  Bengaluru 2015-01-01    NaN           NaN
2015  Bengaluru 2015-01-02    NaN           NaN
2015  Bengaluru 2015-01-03    NaN           NaN
2015  Bengaluru 2015-01-04    NaN           NaN
2015  Bengaluru 2015-01-05    NaN           NaN
...         ...        ...    ...           ...
2015  Bengaluru 2015-12-27  115.0      Moderate
2015  Bengaluru 2015-12-28  149.0      Moderate
2015  Bengaluru 2015-12-29  122.0      Moderate
2015  Bengaluru 2015-12-30   91.0  Satisfactory
2015  Bengaluru 2015-12-31  131.0      Moderate

[365 rows x 4 columns]

# AQI DATAFRAMES

In [15]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [16]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = pd.read_csv('delhi_2017.csv')
aqi_level_18 = pd.read_csv('delhi_2018.csv')
aqi_level_19 = pd.read_csv('delhi_2019.csv')
aqi_level_20 = new_df.loc['2020']

In [17]:
aqi_level_20

City       Date    AQI    AQI_Bucket
Year                                           
2020  Bengaluru 2020-01-01   82.0  Satisfactory
2020  Bengaluru 2020-01-02   81.0  Satisfactory
2020  Bengaluru 2020-01-03   85.0  Satisfactory
2020  Bengaluru 2020-01-04   95.0  Satisfactory
2020  Bengaluru 2020-01-05  118.0      Moderate
...         ...        ...    ...           ...
2020  Bengaluru 2020-06-27   51.0  Satisfactory
2020  Bengaluru 2020-06-28   61.0  Satisfactory
2020  Bengaluru 2020-06-29   65.0  Satisfactory
2020  Bengaluru 2020-06-30   63.0  Satisfactory
2020  Bengaluru 2020-07-01   43.0          Good

[183 rows x 4 columns]

In [18]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,-2],
    x = aqi_level_17.iloc[:,-3]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "AQI LEVELS",
        title_standoff = 25)
fig.update_layout(title_text="AQI 2017")

fig.show()

In [19]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,-2],
    x = aqi_level_18.iloc[:,-3]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "AQI LEVELS",
        title_standoff = 25)
fig.update_layout(title_text="AQI 2018")

fig.show()

In [20]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,-2],
    x = aqi_level_19.iloc[:,-3]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "AQI LEVELS",
        title_standoff = 25)
fig.update_layout(title_text="AQI 2019")

fig.show()

In [21]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,-2],
    x = aqi_level_16.iloc[:,-3]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,-2],
    x = aqi_level_17.iloc[:,-3]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,-2],
    x = aqi_level_18.iloc[:,-3]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,-2],
    x = aqi_level_19.iloc[:,-3]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,-2],
    x = aqi_level_15.iloc[:,-3]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,-2],
                         x = aqi_level_20.iloc[:,-3]),
                         row = 2,col = 3)
fig.update_layout(title_text="AQI IN DIFFERENT YEARS", height=700)
fig.show()


In [22]:
fig = px.scatter_3d(aqi_level_20, x= "AQI", y="Date", z="AQI_Bucket")
fig.show()

In [23]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [24]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [25]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [26]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [27]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [28]:
x_18

array([[ 73.,  86.,  84.,  86.,  95., 102.],
       [ 86.,  84.,  86.,  95., 102., 104.],
       [ 84.,  86.,  95., 102., 104.,  93.],
       ...,
       [ 87.,  79., 103., 118., 117., 123.],
       [ 79., 103., 118., 117., 123., 124.],
       [103., 118., 117., 123., 124., 127.]])

In [29]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [30]:
x_16.shape

(359, 6)

In [31]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [32]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [33]:
ds_5.shape

(1795, 6)

In [34]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [35]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0          NaN       NaN       NaN       NaN       NaN      NaN
1          NaN       NaN       NaN       NaN       NaN      NaN
2          NaN       NaN       NaN       NaN       NaN      NaN
3          NaN       NaN       NaN       NaN       NaN      NaN
4          NaN       NaN       NaN       NaN       NaN      NaN
...        ...       ...       ...       ...       ...      ...
1790      95.0      88.0      92.0      89.0      76.0     95.0
1791      88.0      92.0      89.0      76.0      95.0     98.0
1792      92.0      89.0      76.0      95.0      98.0     82.0
1793      89.0      76.0      95.0      98.0      82.0     80.0
1794      76.0      95.0      98.0      82.0      80.0     93.0

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [36]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [37]:
svr_X

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       ...,
       [92., 89., 76., 95., 98.],
       [89., 76., 95., 98., 82.],
       [76., 95., 98., 82., 80.]])

### Step 2 :Removing the null values 

In [38]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [39]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [40]:
svr_X

array([[95.68573113, 95.75898645, 95.80212014, 95.84755739, 95.85176471],
       [95.68573113, 95.75898645, 95.80212014, 95.84755739, 95.85176471],
       [95.68573113, 95.75898645, 95.80212014, 95.84755739, 95.85176471],
       ...,
       [92.        , 89.        , 76.        , 95.        , 98.        ],
       [89.        , 76.        , 95.        , 98.        , 82.        ],
       [76.        , 95.        , 98.        , 82.        , 80.        ]])

In [41]:
svr_Y

array([[95.83421517],
       [95.83421517],
       [95.83421517],
       ...,
       [82.        ],
       [80.        ],
       [93.        ]])

### Step 3: Test - Train - Split

In [42]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [43]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [44]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [45]:
svr_y_pred.shape


(359,)

In [46]:
svr_y_test.shape

(359, 1)

In [47]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [48]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [49]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.6219083699035985

In [50]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.6239572555430886

In [51]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

0.1677867441306326

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [52]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-52-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [53]:
xg_X.shape

(365, 5)

In [54]:
xg_X[205,:]

array([ 51.,  nan, 164.,  59.,  64.])

In [55]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [56]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [57]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [58]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [59]:
svr_x_train

array([[ 98.,  73., 144.,  99., 151.],
       [120., 148., 133., 143.,  86.],
       [134., 112.,  80.,  84.,  96.],
       ...,
       [122., 103.,  96., 102., 104.],
       [ 96., 123.,  77.,  57.,  63.],
       [133., 143.,  86.,  75.,  86.]])

In [60]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [61]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [62]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.18969144135725846

In [63]:
xg_pred.shape

(365,)

In [64]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.2003030554413281

### Visualization in XgBoost 

In [65]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [66]:
df_xg

Predicted  Actual
0    135.783829    82.0
1    108.151176    81.0
2    142.083420    85.0
3    105.585907    95.0
4    112.381721   118.0
..          ...     ...
178  179.742249    51.0
179  116.553108    61.0
180   76.511345    65.0
181   80.324768    63.0
182  116.750229    43.0

[183 rows x 2 columns]

In [67]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [68]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [69]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [70]:
t=(a-b)/a

In [71]:
t

0.4007906717817143

### 2.) Decision Tree Model

In [72]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [73]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

NameError: name 'x_test' is not defined

### 3.) Random Forest Classification

In [74]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

In [75]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

NameError: name 'x_test' is not defined

In [76]:
aqi_16.shape

(366,)

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])