# Importing Libraries


In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [3]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,4:]],axis = 1)

new_df = new_df[new_df['City'] == 'Bengaluru']

In [4]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [5]:
new_df['Year'] = new_df['Date'].dt.year

In [6]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [7]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [8]:
ds_delhi_16

City       Date     NO    NO2    NOx    NH3    CO   SO2     O3  \
Year                                                                        
2016  Bengaluru 2016-01-01  13.80  51.73  34.31  14.68  0.69  7.44  55.96   
2016  Bengaluru 2016-01-02  26.49  73.09  54.77  16.05  0.76  8.67  34.06   
2016  Bengaluru 2016-01-03  24.56  77.77  55.60  16.37  0.96  9.10  47.62   
2016  Bengaluru 2016-01-04  18.56  77.07  50.81  14.18  0.89  8.87  50.62   
2016  Bengaluru 2016-01-05  23.56  79.43  56.05  16.97  0.85  9.41  36.94   
...         ...        ...    ...    ...    ...    ...   ...   ...    ...   
2016  Bengaluru 2016-12-27   5.22  41.33   0.00  16.90  0.70  7.04  23.74   
2016  Bengaluru 2016-12-28   2.34  20.70   0.00  17.07  0.20  4.32  17.27   
2016  Bengaluru 2016-12-29   7.43  30.07   0.00  16.91  0.46  5.60    NaN   
2016  Bengaluru 2016-12-30   9.58  44.47   0.00  17.46  0.57  5.58    NaN   
2016  Bengaluru 2016-12-31   9.90  47.25   0.00  17.59  0.74  4.92  41.16   

      Benzene  Toluene  Xylene    AQI    AQI_Bucket  
Year                                                 
2016     0.91     0.78     NaN  101.0      Moderate  
2016     1.88     1.18     NaN   92.0  Satisfactory  
2016     2.36     1.14     NaN  108.0      Moderate  
2016     1.95     1.33     NaN  109.0      Moderate  
2016     1.92     1.26     NaN  114.0      Moderate  
...       ...      ...     ...    ...           ...  
2016     3.94     3.79     NaN   90.0  Satisfactory  
2016     3.16     2.63     NaN   84.0  Satisfactory  
2016      NaN      NaN     NaN   76.0  Satisfactory  
2016      NaN      NaN     NaN   93.0  Satisfactory  
2016     2.76     2.06     NaN  106.0      Moderate  

[366 rows x 14 columns]

# AQI DATAFRAMES

In [9]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [10]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [11]:
aqi_level_17

City       Date     NO    NO2    NOx    NH3    CO   SO2     O3  \
Year                                                                        
2017  Bengaluru 2017-01-01   7.33  42.34   0.00    NaN  0.77  4.80  25.90   
2017  Bengaluru 2017-01-02   8.81  40.94   0.00  17.62  0.68  4.93  29.95   
2017  Bengaluru 2017-01-03   9.80  49.02   0.00  19.41  0.74  4.95  31.55   
2017  Bengaluru 2017-01-04   6.90  38.48   0.00  24.85  0.76  4.58  39.09   
2017  Bengaluru 2017-01-05   7.03  36.01   0.00  25.09  0.63  4.57  35.78   
...         ...        ...    ...    ...    ...    ...   ...   ...    ...   
2017  Bengaluru 2017-12-27   6.40  44.73  26.75   9.77  0.91  3.40    NaN   
2017  Bengaluru 2017-12-28   7.00  44.56  25.49  10.45  0.96  3.38  52.72   
2017  Bengaluru 2017-12-29  10.82  48.73  27.48   9.60  1.13  3.60  17.18   
2017  Bengaluru 2017-12-30  10.05  42.60  24.20   8.98  1.06  3.26  33.48   
2017  Bengaluru 2017-12-31  11.90  41.94  24.62    NaN  1.02  2.95  32.36   

      Benzene  Toluene  Xylene    AQI    AQI_Bucket  
Year                                                 
2017     3.65     2.04     NaN   88.0  Satisfactory  
2017     2.35     2.36     NaN   83.0  Satisfactory  
2017     4.07     4.61     NaN   87.0  Satisfactory  
2017     4.02     3.48     NaN   91.0  Satisfactory  
2017     3.12     3.30     NaN   85.0  Satisfactory  
...       ...      ...     ...    ...           ...  
2017     0.00     0.97     NaN   99.0  Satisfactory  
2017     0.00     0.95     NaN  109.0      Moderate  
2017      NaN     1.20     NaN   85.0  Satisfactory  
2017      NaN     1.16     NaN   77.0  Satisfactory  
2017      NaN      NaN     NaN   72.0  Satisfactory  

[365 rows x 14 columns]

In [12]:
aqi_level_17.iloc[:,2],

(Year
 2017     7.33
 2017     8.81
 2017     9.80
 2017     6.90
 2017     7.03
         ...  
 2017     6.40
 2017     7.00
 2017    10.82
 2017    10.05
 2017    11.90
 Name: NO, Length: 365, dtype: float64,)

In [13]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2017")

fig.show()

In [14]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2018")

fig.show()

In [15]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2019")

fig.show()

In [16]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,2],
                         x = aqi_level_20.iloc[:,1]),
                         row = 2,col = 3)
fig.update_layout(title_text="NO IN DIFFERENT YEARS", height=700)
fig.show()


In [17]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [18]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [19]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [20]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [21]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [22]:
x_18

array([[ 9.91,  7.16,  9.57,  6.77,  7.99,  7.64],
       [ 7.16,  9.57,  6.77,  7.99,  7.64,  8.23],
       [ 9.57,  6.77,  7.99,  7.64,  8.23,  5.06],
       ...,
       [ 9.1 , 10.4 , 10.72, 10.07, 12.41,  9.44],
       [10.4 , 10.72, 10.07, 12.41,  9.44, 11.15],
       [10.72, 10.07, 12.41,  9.44, 11.15,  8.74]])

In [23]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [24]:
x_16.shape

(359, 6)

In [25]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [26]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [27]:
ds_5.shape

(1795, 6)

In [28]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [29]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0         3.26      6.05     11.91      7.45      9.52     6.60
1         6.05     11.91      7.45      9.52      6.60    22.60
2        11.91      7.45      9.52      6.60     22.60     7.50
3         7.45      9.52      6.60     22.60      7.50     6.75
4         9.52      6.60     22.60      7.50      6.75     3.38
...        ...       ...       ...       ...       ...      ...
1790      7.89      6.30      8.39      9.20      7.38     7.56
1791      6.30      8.39      9.20      7.38      7.56     9.56
1792      8.39      9.20      7.38      7.56      9.56     7.86
1793      9.20      7.38      7.56      9.56      7.86     6.56
1794      7.38      7.56      9.56      7.86      6.56     6.40

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [30]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [31]:
svr_X

array([[ 3.26,  6.05, 11.91,  7.45,  9.52],
       [ 6.05, 11.91,  7.45,  9.52,  6.6 ],
       [11.91,  7.45,  9.52,  6.6 , 22.6 ],
       ...,
       [ 8.39,  9.2 ,  7.38,  7.56,  9.56],
       [ 9.2 ,  7.38,  7.56,  9.56,  7.86],
       [ 7.38,  7.56,  9.56,  7.86,  6.56]])

### Step 2 :Removing the null values 

In [32]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [33]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [34]:
svr_X

array([[ 3.26,  6.05, 11.91,  7.45,  9.52],
       [ 6.05, 11.91,  7.45,  9.52,  6.6 ],
       [11.91,  7.45,  9.52,  6.6 , 22.6 ],
       ...,
       [ 8.39,  9.2 ,  7.38,  7.56,  9.56],
       [ 9.2 ,  7.38,  7.56,  9.56,  7.86],
       [ 7.38,  7.56,  9.56,  7.86,  6.56]])

In [35]:
svr_Y

array([[ 6.6 ],
       [22.6 ],
       [ 7.5 ],
       ...,
       [ 7.86],
       [ 6.56],
       [ 6.4 ]])

### Step 3: Test - Train - Split

In [36]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [37]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [38]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [39]:
svr_y_pred.shape


(359,)

In [40]:
svr_y_test.shape

(359, 1)

In [41]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [42]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [43]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.44804888087276684

In [44]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.4626180914650957

In [45]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

0.31890413778727594

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [46]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-46-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [47]:
xg_X.shape

(365, 5)

In [48]:
xg_X[205,:]

array([ 4.63,  6.1 , 11.09,  8.78,  7.12])

In [49]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [50]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [51]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [52]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [53]:
svr_x_train

array([[ 5.02,  3.72,  3.63,  3.35, 28.39],
       [28.  , 21.48, 17.62,  8.19,  7.87],
       [11.64,  9.95, 10.  ,  8.75,  9.72],
       ...,
       [ 5.78,  4.8 ,  3.95,  4.23,  8.52],
       [ 4.  ,  5.  ,  4.23,  6.76,  3.22],
       [17.62,  8.19,  7.87, 10.44, 16.43]])

In [54]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [55]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [56]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.41634128468179965

In [57]:
xg_pred.shape

(365,)

In [58]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.16438645119562045

### Visualization in XgBoost 

In [59]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [60]:
df_xg

Predicted  Actual
0    10.345204    9.03
1    12.333943    8.81
2    17.227486    6.62
3    10.468283   15.46
4    15.460678    6.86
..         ...     ...
178   6.383980    3.06
179   9.097887    2.69
180   9.204272    3.62
181   7.827058    4.61
182   8.208689    3.95

[183 rows x 2 columns]

In [61]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 NO Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [62]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [63]:
x=df_xg.iloc[85:,0]-x

In [64]:
np.mean(x)

3.7713265306122454

In [65]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [66]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [67]:
t=(a-b)/a

In [68]:
t

0.5190274333064814

### 2.) Decision Tree Model

In [69]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [ ]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

### 3.) Random Forest Classification

In [ ]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

In [ ]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

In [ ]:
aqi_16.shape

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])