# Importing Libraries


In [1]:
pip install cufflinks


Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [3]:
ds_1=pd.read_csv('city_day.csv');

In [4]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,8:]],axis = 1)

new_df = new_df[new_df['City'] == 'Bengaluru']

In [5]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [6]:
new_df['Year'] = new_df['Date'].dt.year

In [7]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [8]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [9]:
ds_delhi_16

City       Date    CO   SO2     O3  Benzene  Toluene  Xylene  \
Year                                                                      
2016  Bengaluru 2016-01-01  0.69  7.44  55.96     0.91     0.78     NaN   
2016  Bengaluru 2016-01-02  0.76  8.67  34.06     1.88     1.18     NaN   
2016  Bengaluru 2016-01-03  0.96  9.10  47.62     2.36     1.14     NaN   
2016  Bengaluru 2016-01-04  0.89  8.87  50.62     1.95     1.33     NaN   
2016  Bengaluru 2016-01-05  0.85  9.41  36.94     1.92     1.26     NaN   
...         ...        ...   ...   ...    ...      ...      ...     ...   
2016  Bengaluru 2016-12-27  0.70  7.04  23.74     3.94     3.79     NaN   
2016  Bengaluru 2016-12-28  0.20  4.32  17.27     3.16     2.63     NaN   
2016  Bengaluru 2016-12-29  0.46  5.60    NaN      NaN      NaN     NaN   
2016  Bengaluru 2016-12-30  0.57  5.58    NaN      NaN      NaN     NaN   
2016  Bengaluru 2016-12-31  0.74  4.92  41.16     2.76     2.06     NaN   

        AQI    AQI_Bucket  
Year                       
2016  101.0      Moderate  
2016   92.0  Satisfactory  
2016  108.0      Moderate  
2016  109.0      Moderate  
2016  114.0      Moderate  
...     ...           ...  
2016   90.0  Satisfactory  
2016   84.0  Satisfactory  
2016   76.0  Satisfactory  
2016   93.0  Satisfactory  
2016  106.0      Moderate  

[366 rows x 10 columns]

# AQI DATAFRAMES

In [10]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [11]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [12]:
aqi_level_17

City       Date    CO   SO2     O3  Benzene  Toluene  Xylene  \
Year                                                                      
2017  Bengaluru 2017-01-01  0.77  4.80  25.90     3.65     2.04     NaN   
2017  Bengaluru 2017-01-02  0.68  4.93  29.95     2.35     2.36     NaN   
2017  Bengaluru 2017-01-03  0.74  4.95  31.55     4.07     4.61     NaN   
2017  Bengaluru 2017-01-04  0.76  4.58  39.09     4.02     3.48     NaN   
2017  Bengaluru 2017-01-05  0.63  4.57  35.78     3.12     3.30     NaN   
...         ...        ...   ...   ...    ...      ...      ...     ...   
2017  Bengaluru 2017-12-27  0.91  3.40    NaN     0.00     0.97     NaN   
2017  Bengaluru 2017-12-28  0.96  3.38  52.72     0.00     0.95     NaN   
2017  Bengaluru 2017-12-29  1.13  3.60  17.18      NaN     1.20     NaN   
2017  Bengaluru 2017-12-30  1.06  3.26  33.48      NaN     1.16     NaN   
2017  Bengaluru 2017-12-31  1.02  2.95  32.36      NaN      NaN     NaN   

        AQI    AQI_Bucket  
Year                       
2017   88.0  Satisfactory  
2017   83.0  Satisfactory  
2017   87.0  Satisfactory  
2017   91.0  Satisfactory  
2017   85.0  Satisfactory  
...     ...           ...  
2017   99.0  Satisfactory  
2017  109.0      Moderate  
2017   85.0  Satisfactory  
2017   77.0  Satisfactory  
2017   72.0  Satisfactory  

[365 rows x 10 columns]

In [13]:
aqi_level_17.iloc[:,2],

(Year
 2017    0.77
 2017    0.68
 2017    0.74
 2017    0.76
 2017    0.63
         ... 
 2017    0.91
 2017    0.96
 2017    1.13
 2017    1.06
 2017    1.02
 Name: CO, Length: 365, dtype: float64,)

In [14]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2017")

fig.show()

In [15]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2018")

fig.show()

In [16]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2019")

fig.show()

In [17]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,2],
                         x = aqi_level_20.iloc[:,1]),
                         row = 2,col = 3)
fig.update_layout(title_text="CO IN DIFFERENT YEARS", height=700)
fig.show()


In [18]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [19]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [20]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [21]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [22]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [23]:
x_18

array([[1.04, 1.  , 1.09, 0.96, 1.04, 0.98],
       [1.  , 1.09, 0.96, 1.04, 0.98, 0.99],
       [1.09, 0.96, 1.04, 0.98, 0.99, 0.93],
       ...,
       [0.82, 0.85, 0.93, 1.01, 0.9 , 0.91],
       [0.85, 0.93, 1.01, 0.9 , 0.91, 0.89],
       [0.93, 1.01, 0.9 , 0.91, 0.89, 0.85]])

In [24]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [25]:
x_16.shape

(359, 6)

In [26]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [27]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [28]:
ds_5.shape

(1795, 6)

In [29]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [30]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0         0.33      1.35     17.40      5.05      1.83     0.52
1         1.35     17.40      5.05      1.83      0.52     1.46
2        17.40      5.05      1.83      0.52      1.46     2.30
3         5.05      1.83      0.52      1.46      2.30     0.54
4         1.83      0.52      1.46      2.30      0.54     1.69
...        ...       ...       ...       ...       ...      ...
1790      0.98      0.91      1.00      1.13      1.03     1.03
1791      0.91      1.00      1.13      1.03      1.03     1.09
1792      1.00      1.13      1.03      1.03      1.09     0.97
1793      1.13      1.03      1.03      1.09      0.97     0.92
1794      1.03      1.03      1.09      0.97      0.92     1.03

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [31]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [32]:
svr_X

array([[ 0.33,  1.35, 17.4 ,  5.05,  1.83],
       [ 1.35, 17.4 ,  5.05,  1.83,  0.52],
       [17.4 ,  5.05,  1.83,  0.52,  1.46],
       ...,
       [ 1.  ,  1.13,  1.03,  1.03,  1.09],
       [ 1.13,  1.03,  1.03,  1.09,  0.97],
       [ 1.03,  1.03,  1.09,  0.97,  0.92]])

### Step 2 :Removing the null values 

In [33]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [34]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [35]:
svr_X

array([[ 0.33,  1.35, 17.4 ,  5.05,  1.83],
       [ 1.35, 17.4 ,  5.05,  1.83,  0.52],
       [17.4 ,  5.05,  1.83,  0.52,  1.46],
       ...,
       [ 1.  ,  1.13,  1.03,  1.03,  1.09],
       [ 1.13,  1.03,  1.03,  1.09,  0.97],
       [ 1.03,  1.03,  1.09,  0.97,  0.92]])

In [36]:
svr_Y

array([[0.52],
       [1.46],
       [2.3 ],
       ...,
       [0.97],
       [0.92],
       [1.03]])

### Step 3: Test - Train - Split

In [37]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [38]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [39]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [40]:
svr_y_pred.shape


(359,)

In [41]:
svr_y_test.shape

(359, 1)

In [42]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [43]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [44]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.4449138477037984

In [45]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.46190498574885475

In [46]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

48087019436394.59

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [47]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-47-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [48]:
xg_X.shape

(365, 5)

In [49]:
xg_X[205,:]

array([2.89, 5.23, 1.4 , 0.94, 0.77])

In [50]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [51]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [52]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [53]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [54]:
svr_x_train

array([[0.88, 1.16, 0.72, 0.73, 0.91],
       [1.05, 1.1 , 1.06, 0.78, 0.57],
       [1.25, 0.96, 0.81, 0.82, 0.9 ],
       ...,
       [1.16, 1.14, 1.14, 1.24, 1.19],
       [1.16, 4.29, 1.43, 2.4 , 1.96],
       [1.06, 0.78, 0.57, 0.79, 0.94]])

In [55]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [56]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [57]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.41669238016500987

In [58]:
xg_pred.shape

(365,)

In [59]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

-0.67167005332747

### Visualization in XgBoost 

In [60]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [61]:
df_xg

Predicted  Actual
0     0.880187    1.07
1     0.789753    1.16
2     1.306996    0.99
3     2.074685    1.39
4     1.265689    1.01
..         ...     ...
178   0.824486    0.67
179   5.418756    0.66
180   0.480179    0.56
181   2.512458    0.56
182  -0.265723    0.54

[183 rows x 2 columns]

In [62]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 CO Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [63]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [64]:
x=df_xg.iloc[85:,0]-x

In [65]:
np.mean(x)

0.7171428571428573

In [66]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [67]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [68]:
t=(a-b)/a

In [69]:
t

0.48399999526215187

### 2.) Decision Tree Model

In [70]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [ ]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

### 3.) Random Forest Classification

In [ ]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

In [ ]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

In [ ]:
aqi_16.shape

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])