# Importing Libraries


In [3]:
pip install cufflinks


  Using cached cufflinks-0.17.3.tar.gz (81 kB)
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Note: you may need to restart the kernel to use updated packages.
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68724 sha256=227e1b0974b1db5ea9802bc42473a2fd2cf2d4f87d84d5f9f7d9afd60b4e1f64
  Stored in directory: c:\users\payus\appdata\local\pip\cache\wheels\6b\76\62\6da97734911ffcbdd559fd1a3f28526321f0ae699182a23866
Successfully built cufflinks


In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [3]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,8:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [4]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [5]:
new_df['Year'] = new_df['Date'].dt.year

In [6]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [7]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [8]:
ds_delhi_16

City       Date    CO    SO2      O3  Benzene  Toluene  Xylene    AQI  \
Year                                                                           
2016  Delhi 2016-01-01  2.42  23.57  108.14     5.81    16.30     0.0  463.0   
2016  Delhi 2016-01-02  2.15  23.33   90.45     5.79    17.65     NaN  465.0   
2016  Delhi 2016-01-03  2.39  19.94   97.03     5.33    10.78     NaN  426.0   
2016  Delhi 2016-01-04  2.97  27.90   91.20     7.12    19.01     NaN  496.0   
2016  Delhi 2016-01-05  2.85  30.24  131.40     6.45    21.32     NaN  528.0   
...     ...        ...   ...    ...     ...      ...      ...     ...    ...   
2016  Delhi 2016-12-27  0.94  24.51   36.90     6.13    11.06     NaN  319.0   
2016  Delhi 2016-12-28  1.61  26.10   40.19     7.04    16.43     NaN  455.0   
2016  Delhi 2016-12-29  1.30  21.60   55.09     7.29    18.01     NaN  524.0   
2016  Delhi 2016-12-30  0.96  23.47   43.97     6.93    12.43     NaN  381.0   
2016  Delhi 2016-12-31  1.14  23.82   42.84     8.03    17.16     NaN  338.0   

     AQI_Bucket  
Year             
2016     Severe  
2016     Severe  
2016     Severe  
2016     Severe  
2016     Severe  
...         ...  
2016  Very Poor  
2016     Severe  
2016     Severe  
2016  Very Poor  
2016  Very Poor  

[366 rows x 10 columns]

# AQI DATAFRAMES

In [9]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [10]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [11]:
aqi_level_17

City       Date    CO    SO2     O3  Benzene  Toluene  Xylene    AQI  \
Year                                                                          
2017  Delhi 2017-01-01  1.31  25.13  50.03     8.39    19.94     NaN  332.0   
2017  Delhi 2017-01-02  1.47  22.29  47.86     8.96    18.92     NaN  384.0   
2017  Delhi 2017-01-03  1.28  25.33  42.90     7.65    13.96     NaN  373.0   
2017  Delhi 2017-01-04  1.55  23.11  41.13     7.26    16.51     NaN  439.0   
2017  Delhi 2017-01-05  1.24  25.15  41.95     5.73    12.89     NaN  318.0   
...     ...        ...   ...    ...    ...      ...      ...     ...    ...   
2017  Delhi 2017-12-27  1.69  23.17  58.98     5.95    18.27    0.03  379.0   
2017  Delhi 2017-12-28  1.86  25.51  66.00     6.36    23.66    0.00  398.0   
2017  Delhi 2017-12-29  1.70  25.54  61.36     5.35    19.38    0.77  399.0   
2017  Delhi 2017-12-30  1.96  21.01  61.73     6.96    25.19    1.18  421.0   
2017  Delhi 2017-12-31  1.95  17.97  76.45     7.01    21.12    0.35  451.0   

     AQI_Bucket  
Year             
2017  Very Poor  
2017  Very Poor  
2017  Very Poor  
2017     Severe  
2017  Very Poor  
...         ...  
2017  Very Poor  
2017  Very Poor  
2017  Very Poor  
2017     Severe  
2017     Severe  

[365 rows x 10 columns]

In [12]:
aqi_level_17.iloc[:,2],

(Year
 2017    1.31
 2017    1.47
 2017    1.28
 2017    1.55
 2017    1.24
         ... 
 2017    1.69
 2017    1.86
 2017    1.70
 2017    1.96
 2017    1.95
 Name: CO, Length: 365, dtype: float64,)

In [13]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2017")

fig.show()

In [14]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2018")

fig.show()

In [15]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "CO",
        title_standoff = 25)
fig.update_layout(title_text="CO 2019")

fig.show()

In [16]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,2],
                         x = aqi_level_20.iloc[:,1]),
                         row = 2,col = 3)
fig.update_layout(title_text="CO IN DIFFERENT YEARS", height=700)
fig.show()


In [24]:
fig = px.scatter_3d(aqi_level_20, x= "PM10", y="Date", z="AQI_Bucket")
fig.show()

In [17]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [18]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [19]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [20]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [21]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [22]:
x_18

array([[1.8 , 1.52, 1.29, 1.36, 1.38, 1.59],
       [1.52, 1.29, 1.36, 1.38, 1.59, 1.3 ],
       [1.29, 1.36, 1.38, 1.59, 1.3 , 1.33],
       ...,
       [3.36, 3.36, 1.9 , 1.99, 2.87, 1.66],
       [3.36, 1.9 , 1.99, 2.87, 1.66, 1.96],
       [1.9 , 1.99, 2.87, 1.66, 1.96, 2.94]])

In [23]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [24]:
x_16.shape

(359, 6)

In [25]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [26]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [27]:
ds_5.shape

(1795, 6)

In [28]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [29]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0        15.20      9.54     10.61     11.54      9.20     9.44
1         9.54     10.61     11.54      9.20      9.44     9.78
2        10.61     11.54      9.20      9.44      9.78    11.01
3        11.54      9.20      9.44      9.78     11.01    11.09
4         9.20      9.44      9.78     11.01     11.09     9.70
...        ...       ...       ...       ...       ...      ...
1790      1.71      1.13      1.28      1.76      1.20     1.17
1791      1.13      1.28      1.76      1.20      1.17     1.39
1792      1.28      1.76      1.20      1.17      1.39     1.96
1793      1.76      1.20      1.17      1.39      1.96     1.86
1794      1.20      1.17      1.39      1.96      1.86     2.24

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [30]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [31]:
svr_X

array([[15.2 ,  9.54, 10.61, 11.54,  9.2 ],
       [ 9.54, 10.61, 11.54,  9.2 ,  9.44],
       [10.61, 11.54,  9.2 ,  9.44,  9.78],
       ...,
       [ 1.28,  1.76,  1.2 ,  1.17,  1.39],
       [ 1.76,  1.2 ,  1.17,  1.39,  1.96],
       [ 1.2 ,  1.17,  1.39,  1.96,  1.86]])

### Step 2 :Removing the null values 

In [32]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [33]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [34]:
svr_X

array([[15.2 ,  9.54, 10.61, 11.54,  9.2 ],
       [ 9.54, 10.61, 11.54,  9.2 ,  9.44],
       [10.61, 11.54,  9.2 ,  9.44,  9.78],
       ...,
       [ 1.28,  1.76,  1.2 ,  1.17,  1.39],
       [ 1.76,  1.2 ,  1.17,  1.39,  1.96],
       [ 1.2 ,  1.17,  1.39,  1.96,  1.86]])

In [35]:
svr_Y

array([[ 9.44],
       [ 9.78],
       [11.01],
       ...,
       [ 1.96],
       [ 1.86],
       [ 2.24]])

### Step 3: Test - Train - Split

In [36]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [37]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [38]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [39]:
svr_y_pred.shape


(359,)

In [40]:
svr_y_test.shape

(359, 1)

In [41]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [42]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [43]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.7141962907577694

In [44]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.7152980513249608

In [45]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

20369470166386.38

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [46]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-46-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [47]:
xg_X.shape

(365, 5)

In [48]:
xg_X[205,:]

array([1.  , 1.45, 0.  , 0.81, 0.94])

In [49]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [50]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [51]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [52]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [53]:
svr_x_train

array([[1.23, 1.17, 1.74, 2.05, 2.2 ],
       [1.56, 1.77, 2.18, 2.28, 1.51],
       [0.96, 1.36, 1.78, 2.09, 1.94],
       ...,
       [1.31, 1.51, 1.87, 1.43, 1.32],
       [0.97, 0.93, 1.08, 1.35, 1.64],
       [2.18, 2.28, 1.51, 1.34, 1.31]])

In [54]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [55]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [56]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.317979492614769

In [57]:
xg_pred.shape

(365,)

In [58]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.6391514199906014

### Visualization in XgBoost 

In [59]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [60]:
df_xg

Predicted  Actual
0     1.858190    3.15
1     1.852502    3.32
2     2.561461    2.80
3     1.331963    2.20
4     0.928928    1.23
..         ...     ...
178   1.165438    0.87
179   1.510927    0.94
180   1.158630    0.88
181   1.250482    0.84
182   1.252611    0.97

[183 rows x 2 columns]

In [61]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 CO Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [62]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [63]:
x=df_xg.iloc[85:,0]-x

In [64]:
np.mean(x)

0.8502040816326528

In [65]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [66]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [67]:
t=(a-b)/a

In [68]:
t

0.3358279317760569

### 2.) Decision Tree Model

In [89]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [90]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

NameError: name 'x_test' is not defined

### 3.) Random Forest Classification

In [91]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

In [92]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

NameError: name 'x_test' is not defined

In [93]:
aqi_16.shape

(366,)

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])