# Importing Libraries


In [1]:
import pandas as pd;
import numpy as np;

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [3]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,-2:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [4]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [5]:
new_df['Year'] = new_df['Date'].dt.year

In [6]:
new_df = new_df.set_index(['Year'])

In [7]:
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [8]:
ds_delhi_16

City       Date    AQI AQI_Bucket
Year                                    
2016  Delhi 2016-01-01  463.0     Severe
2016  Delhi 2016-01-02  465.0     Severe
2016  Delhi 2016-01-03  426.0     Severe
2016  Delhi 2016-01-04  496.0     Severe
2016  Delhi 2016-01-05  528.0     Severe
...     ...        ...    ...        ...
2016  Delhi 2016-12-27  319.0  Very Poor
2016  Delhi 2016-12-28  455.0     Severe
2016  Delhi 2016-12-29  524.0     Severe
2016  Delhi 2016-12-30  381.0  Very Poor
2016  Delhi 2016-12-31  338.0  Very Poor

[366 rows x 4 columns]

In [9]:
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

In [10]:
x_17=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [11]:
x_16=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [12]:
x_18=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [13]:
x_18

array([[462., 439., 405., 394.],
       [439., 405., 394., 398.],
       [405., 394., 398., 403.],
       ...,
       [405., 458., 413., 420.],
       [458., 413., 420., 484.],
       [413., 420., 484., 509.]])

In [14]:
x_19=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [15]:
x_16.shape

(362, 4)

In [16]:
x_17.shape

(362, 4)

In [17]:
ds_3=np.concatenate((x_16,x_17,x_18),axis=0);

In [18]:
ds_3.shape

(1086, 4)

In [75]:
ds_3= pd.DataFrame(ds_3, columns = ['last 3rd','last 2nd','last 1st','present'])

In [76]:
X=ds_3.iloc[:,[0,1,2]].values;
Y=ds_3.iloc[:,[-1]].values;

In [77]:
X

array([[463., 465., 426.],
       [465., 426., 496.],
       [426., 496., 528.],
       ...,
       [405., 458., 413.],
       [458., 413., 420.],
       [413., 420., 484.]])

In [135]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(X);
X=ds_imputer.transform(X);

In [136]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(Y);
Y=ds_imputer.transform(Y);

In [137]:
X

array([[463., 465., 426.],
       [465., 426., 496.],
       [426., 496., 528.],
       ...,
       [405., 458., 413.],
       [458., 413., 420.],
       [413., 420., 484.]])

In [138]:
Y

array([[496.],
       [528.],
       [538.],
       ...,
       [420.],
       [484.],
       [509.]])

In [139]:
from sklearn.model_selection import train_test_split;
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1);

In [140]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(x_train, np.ravel(y_train));

In [141]:
y_pred=regressor.predict(x_test);

In [142]:
y_pred

array([ 190.36090357,  191.57030011,  185.47264273,  319.76939382,
        190.3750574 ,  248.94056286,  181.39389158,  520.49288266,
        169.35729059,  266.56130168,  199.29422607,  234.78333684,
        212.33294889,  209.58982642,  316.18661339,  196.53908199,
        225.54154951,  318.43908733,  226.70084695,  372.9219436 ,
        219.22690773,  214.50842439,  189.93050996,  301.63274729,
        200.13513906,  218.71518209,  314.38087198,  302.05534413,
        312.98641097,  297.49830345,  296.5952924 ,  168.82933133,
        215.8445369 ,  273.18655414,  318.76640968,  207.87494677,
        190.86875576,  234.05482189,  167.88562821,  267.63015631,
        244.42433417,  225.96307651,  280.86165047,  263.62913908,
        171.21807211,  172.38157273,  251.31710208,  223.36470304,
        208.70234249,  222.42753647,  179.4919164 ,  213.65749626,
        417.13229718,  481.7857247 ,  568.6083533 ,  514.73341484,
        168.12149123,  449.97205605,  205.69946893, 1282.60717

In [143]:
x_test

array([[223.        , 196.        , 183.        ],
       [207.        , 176.        , 189.        ],
       [267.61710037, 111.        , 148.        ],
       [375.        , 330.        , 347.        ],
       [109.        , 154.        , 216.        ],
       [342.        , 297.        , 275.        ],
       [165.        , 102.        , 159.        ],
       [613.        , 561.        , 444.        ],
       [ 96.        ,  92.        ,  95.        ],
       [265.        , 301.        , 322.        ],
       [231.        , 208.        , 207.        ],
       [361.        , 330.        , 256.        ],
       [202.        , 203.        , 246.        ],
       [450.        , 340.        , 203.        ],
       [335.        , 329.        , 356.        ],
       [242.        , 267.        , 207.        ],
       [216.        , 242.        , 271.        ],
       [349.        , 396.        , 363.        ],
       [192.        , 264.        , 284.        ],
       [372.        , 379.     

In [144]:
from sklearn.metrics import accuracy_score,confusion_matrix;

In [145]:
y_test=np.ravel(y_test);
y_pred=np.ravel(y_pred);

In [146]:
ac=y_test-y_pred

In [148]:
ac

array([ -36.36090357,  149.42969989,  -77.47264273,  -45.76939382,
         71.6249426 ,   32.05943714,   -7.39389158, -142.49288266,
        -64.35729059,   24.43869832,  106.70577393,    2.21666316,
         80.66705111,   26.41017358,   77.81338661,  -20.53908199,
        218.45845049,   65.56091267,  -76.70084695,   26.0780564 ,
        -17.22690773,   -1.50842439,   34.06949004,   31.36725271,
         22.86486094,   44.28481791,   -2.38087198,  -87.05534413,
         32.01358903,   72.50169655,  -39.5952924 ,  -62.82933133,
         23.1554631 ,    1.81344586,  -40.76640968,   88.12505323,
        -20.86875576,    0.94517811,  -67.88562821,   37.36984369,
         21.57566583,   74.03692349,   35.13834953,   61.37086092,
        -49.21807211,  -37.38157273,   62.68289792,   60.63529696,
         80.29765751,  -52.42753647,  -25.4919164 ,   88.34250374,
         61.86770282,  -68.7857247 , -131.6083533 ,  -72.73341484,
        -69.12149123,  -49.97205605,   48.30053107, -740.60717

In [149]:
sum=np.zeros(218);
for i in range(0,218,1):
    sum[i]=ac[i]/218;

In [150]:
sum

array([-0.16679314,  0.68545734, -0.3553791 , -0.20995135,  0.32855478,
        0.14706164, -0.03391693, -0.65363708, -0.29521693,  0.11210412,
        0.48947603,  0.01016818,  0.37003234,  0.12114759,  0.35694214,
       -0.09421597,  1.00210298,  0.30073813, -0.35183875,  0.11962411,
       -0.07902251, -0.00691938,  0.15628206,  0.14388648,  0.10488468,
        0.20314137, -0.01092143, -0.39933644,  0.14685133,  0.33257659,
       -0.18162978, -0.28820794,  0.10621772,  0.00831856, -0.18700188,
        0.40424336, -0.09572824,  0.00433568, -0.31140196,  0.1714213 ,
        0.09897094,  0.33961892,  0.16118509,  0.28151771, -0.22577097,
       -0.1714751 ,  0.28753623,  0.27814356,  0.36833788, -0.24049329,
       -0.1169354 ,  0.40524084,  0.2837968 , -0.31553085, -0.60370804,
       -0.33363952, -0.31707106, -0.22922961,  0.22156207, -3.39728062,
       -0.38773367,  0.50122703,  0.03656037,  0.19503507, -0.29334103,
       -0.2871606 ,  0.22940606, -0.39899498, -0.16109364,  0.25

In [151]:
div=y_test+y_pred

In [152]:
per=ac/div;

In [153]:
per

array([-0.10558952,  0.28058211, -0.26398591, -0.07708278,  0.15833088,
        0.06049629, -0.02080478, -0.158591  , -0.23457474,  0.04383141,
        0.21117553,  0.00469848,  0.15963149,  0.05927014,  0.10956752,
       -0.05513269,  0.32628065,  0.09333324, -0.20361209,  0.03378328,
       -0.04089698, -0.00352841,  0.08230727,  0.04942583,  0.05403678,
        0.09193154, -0.003801  , -0.16836756,  0.04865388,  0.10861705,
       -0.0715239 , -0.22861218,  0.05090852,  0.00330808, -0.06831217,
        0.17489469, -0.05782921,  0.00201507, -0.25341273,  0.06526   ,
        0.04227006,  0.14076449,  0.05887185,  0.10426066, -0.16785484,
       -0.12161293,  0.11088095,  0.11951028,  0.16133671, -0.13359801,
       -0.07643938,  0.17132012,  0.06903858, -0.07687396, -0.13087436,
       -0.07602266, -0.25876425, -0.05879259,  0.1050698 , -0.40589952,
       -0.33209165,  0.18249801,  0.00654349,  0.09718711, -0.16399183,
       -0.22309617,  0.11630638, -0.17643869, -0.08379115,  0.07

In [154]:
per*=100

In [155]:
len(per)

218

In [156]:
abs(per[0])

10.558952306684342

In [157]:
ans=0;
for i in range(0,218,1):
    ans+=abs(per[i]);

In [158]:
ans/=218


In [159]:
ans

12.256669824841028

In [160]:
aqi_20

array([492., 485., 426., 366., 354., 335., 285., 281., 231., 255., 309.,
       352., 381., 314., 241., 286., 287., 262., 290., 282., 359., 378.,
       273., 155., 251., 349., 365., 302., 218., 195., 203., 244., 254.,
       297., 336., 344., 277., 307., 315., 310., 328., 347., 343., 279.,
       186., 174., 254., 323., 292., 300., 253., 170., 104., 221., 169.,
       244., 303., 270., 214., 144., 105., 192., 226., 200., 112.,  82.,
        77., 156., 138., 186., 128., 125., 170., 131., 124., 148., 164.,
       162., 191., 209., 205., 198., 127., 124.,  92.,  93.,  76.,  51.,
        64.,  74.,  81.,  80.,  78.,  84.,  90., 103., 134., 100.,  91.,
        89., 111., 126., 102., 119., 134., 152., 172., 123., 102.,  95.,
       115., 102., 122., 129., 143., 121., 119.,  98., 105., 123., 128.,
       140., 127., 110.,  92., 117., 139., 140., 138., 142., 127., 113.,
       122., 132., 154., 125., 175., 202., 222., 238., 196., 149., 199.,
       202., 174., 157., 153., 156., 174., 129.,  8

In [131]:
aqi_20.shape

(183,)

In [132]:
ds_4=np.zeros((183,4));

In [133]:
ds_4[0][0]=420;
ds_4[0][1]=484;
ds_4[0][2]=509;
ds_4[0][3]=regressor.predict([[420,484,509]]);

In [134]:
np.set_printoptions(suppress=True)

In [72]:
for i in range(1,183,1):
    for j in range(0,4,1):
        if(j == 3):
            print(" - ",regressor.predict([[ds_4[i][0], ds_4[i][1], ds_4[i][2]]]));
            ds_4[i][j]=regressor.predict([[ds_4[i][0], ds_4[i][1], ds_4[i][2]]]);
        if(j < 3):
            ds_4[i][j]=ds_4[i-1][j+1];

 -  [718.10386319]
 -  [1214.6894177]
 -  [4333.39988033]
 -  [140952.30234478]
 -  [3.90384219e+09]
 -  [8.13469889e+22]
 -  [7.36008651e+62]
 -  [5.4513897e+182]
 -  [nan]


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [71]:
print(ds_4)

[[420.         484.         509.         560.67661878]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.    

In [ ]:
regressor.predict([[484, 509, 560]])