# Importing Libraries


In [3]:
import pandas as pd;
import numpy as np;

## Importing DataSet

In [4]:
ds_1=pd.read_csv('city_day.csv');

In [5]:
print(ds_1);



                City        Date  PM2.5   PM10     NO    NO2    NOx    NH3  \
0          Ahmedabad  2015-01-01    NaN    NaN   0.92  18.22  17.15    NaN   
1          Ahmedabad  2015-01-02    NaN    NaN   0.97  15.69  16.46    NaN   
2          Ahmedabad  2015-01-03    NaN    NaN  17.40  19.30  29.70    NaN   
3          Ahmedabad  2015-01-04    NaN    NaN   1.70  18.48  17.97    NaN   
4          Ahmedabad  2015-01-05    NaN    NaN  22.10  21.42  37.76    NaN   
...              ...         ...    ...    ...    ...    ...    ...    ...   
29526  Visakhapatnam  2020-06-27  15.02  50.94   7.68  25.06  19.54  12.47   
29527  Visakhapatnam  2020-06-28  24.38  74.09   3.42  26.06  16.53  11.99   
29528  Visakhapatnam  2020-06-29  22.91  65.73   3.45  29.53  18.33  10.71   
29529  Visakhapatnam  2020-06-30  16.64  49.97   4.05  29.26  18.80  10.03   
29530  Visakhapatnam  2020-07-01  15.00  66.00   0.40  26.85  14.05   5.20   

          CO    SO2      O3  Benzene  Toluene  Xylene   AQI    

## Cleaning DataSet

The Dataset we are looking is for Delhi. We can change the city manually and see the data of it.


In [6]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,-2:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [7]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [8]:
new_df['Year'] = new_df['Date'].dt.year

In [9]:
new_df = new_df.set_index(['Year'])

In [10]:
new_df.loc['2017']

City       Date    AQI AQI_Bucket
Year                                    
2017  Delhi 2017-01-01  332.0  Very Poor
2017  Delhi 2017-01-02  384.0  Very Poor
2017  Delhi 2017-01-03  373.0  Very Poor
2017  Delhi 2017-01-04  439.0     Severe
2017  Delhi 2017-01-05  318.0  Very Poor
...     ...        ...    ...        ...
2017  Delhi 2017-12-27  379.0  Very Poor
2017  Delhi 2017-12-28  398.0  Very Poor
2017  Delhi 2017-12-29  399.0  Very Poor
2017  Delhi 2017-12-30  421.0     Severe
2017  Delhi 2017-12-31  451.0     Severe

[365 rows x 4 columns]

In [11]:
ds_delhi_16 = new_df.loc['2016'];
ds_delhi_17 = new_df.loc['2017'];
ds_delhi_18 = new_df.loc['2018'];
ds_delhi_19 = new_df.loc['2019'];
ds_delhi_20 = new_df.loc['2020'];

In [12]:
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

In [13]:
x_16 = np.zeros((362,4))

In [14]:
point = 0 
count = 0
for i in range(0,362):
    for j in range(0,4):
        x_16[i][j] = aqi_16[point]
        point += 1
    count += 1
    point = count


In [15]:
x_16 = pd.DataFrame(x_16)

In [16]:
x_16


0      1      2      3
0    463.0  465.0  426.0  496.0
1    465.0  426.0  496.0  528.0
2    426.0  496.0  528.0  538.0
3    496.0  528.0  538.0  535.0
4    528.0  538.0  535.0  603.0
..     ...    ...    ...    ...
357  470.0  576.0  412.0  338.0
358  576.0  412.0  338.0  319.0
359  412.0  338.0  319.0  455.0
360  338.0  319.0  455.0  524.0
361  319.0  455.0  524.0  381.0

[362 rows x 4 columns]

In [17]:
aqi_16

array([463., 465., 426., 496., 528., 538., 535., 603., 408., 368., 404.,
       444., 356., 397., 371., 311., 321., 424., 435., 455., 398., 399.,
       469., 488., 401., 446., 456., 451., 501., 505., 437., 305., 292.,
       306., 300., 371., 408., 343., 301., 322., 368., 349., 334., 333.,
       257., 265., 297., 289., 310., 366., 345., 228., 213., 208., 319.,
       315., 293., 342., 338., 344., 370., 365., 348., 312., 214., 165.,
       218., 230., 248., 276., 213., 127., 112., 111., 193., 123., 194.,
       186., 242., 267., 207., 176., 189., 341., 325., 259., 178., 219.,
       206., 221., 298., 316., 294., 314., 334., 261., 208., 289., 216.,
       314., 262., 257., 235., 239., 239., 302., 296., 247., 265., 301.,
       322., 291., 292., 258., 282., 271., 314., 377., 390., 392., 342.,
       297., 275., 281., 309., 262., 194., 229., 246., 225., 221., 185.,
       218., 310., 307., 325., 316., 302., 318., 300., 246., 255., 218.,
       252., 190., 256., 311., 381., 409., 269., 18

In [18]:
x_17 = np.zeros((362,4))
x_18 = np.zeros((362,4))
x_19 = np.zeros((362,4))

In [19]:
point = 0 
count = 0
for i in range(0,362):
    for j in range(0,4):
        x_17[i][j] = aqi_17[point]
        point += 1
    count += 1
    point = count

In [20]:
point = 0 
count = 0
for i in range(0,362):
    for j in range(0,4):
        x_18[i][j] = aqi_18[point]
        point += 1
    count += 1
    point = count

In [21]:
point = 0 
count = 0
for i in range(0,362):
    for j in range(0,4):
        x_19[i][j] = aqi_19[point]
        point += 1
    count += 1
    point = count

In [22]:
x_17

array([[332., 384., 373., 439.],
       [384., 373., 439., 318.],
       [373., 439., 318., 390.],
       ...,
       [372., 379., 398., 399.],
       [379., 398., 399., 421.],
       [398., 399., 421., 451.]])

In [23]:
x_18

array([[462., 439., 405., 394.],
       [439., 405., 394., 398.],
       [405., 394., 398., 403.],
       ...,
       [405., 458., 413., 420.],
       [458., 413., 420., 484.],
       [413., 420., 484., 509.]])

In [24]:
x_19

array([[475., 501., 537., 432.],
       [501., 537., 432., 440.],
       [537., 432., 440., 371.],
       ...,
       [340., 372., 425., 455.],
       [372., 425., 455., 506.],
       [425., 455., 506., 417.]])

In [25]:
x_16 = pd.DataFrame(x_16)
x_17 = pd.DataFrame(x_17)
x_18 = pd.DataFrame(x_18)
x_19 = pd.DataFrame(x_19)

In [26]:
x_19

0      1      2      3
0    475.0  501.0  537.0  432.0
1    501.0  537.0  432.0  440.0
2    537.0  432.0  440.0  371.0
3    432.0  440.0  371.0  331.0
4    440.0  371.0  331.0  340.0
..     ...    ...    ...    ...
357  376.0  384.0  340.0  372.0
358  384.0  340.0  372.0  425.0
359  340.0  372.0  425.0  455.0
360  372.0  425.0  455.0  506.0
361  425.0  455.0  506.0  417.0

[362 rows x 4 columns]

## Making Dataframe for Test and Train

In [46]:

ds_2 = np.concatenate((x_16,x_17,x_18,x_19),axis = 0)

ds_2 = pd.DataFrame(ds_2,columns =['Last 3','Last 2','Last 1','Present'])

ds_2

Last 3  Last 2  Last 1  Present
0      463.0   465.0   426.0    496.0
1      465.0   426.0   496.0    528.0
2      426.0   496.0   528.0    538.0
3      496.0   528.0   538.0    535.0
4      528.0   538.0   535.0    603.0
...      ...     ...     ...      ...
1443   376.0   384.0   340.0    372.0
1444   384.0   340.0   372.0    425.0
1445   340.0   372.0   425.0    455.0
1446   372.0   425.0   455.0    506.0
1447   425.0   455.0   506.0    417.0

[1448 rows x 4 columns]

## Here we show that our DataFrame contains some null values so we remove in it next step

In [47]:
ds_2_null = np.where(ds_2['Last 3'].isnull())[0]

In [48]:
ds_2_null

array([205, 535, 586, 587, 595, 596, 599, 600, 601, 602], dtype=int64)

In [50]:
ds_2.iloc[ 205]

Last 3       NaN
Last 2     195.0
Last 1     163.0
Present    108.0
Name: 205, dtype: float64

# Data Preprocessing


Here we remove the null values and make dataset more clean.


In [157]:
X=ds_2.iloc[:,[0,1,2]].values;
Y=ds_2.iloc[:,[-1]].values;

Here we remove the null values of "X"


In [158]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(X);
X=ds_imputer.transform(X);

Now we will remove the Null values of "Y"

In [159]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(Y);
Y=ds_imputer.transform(Y);

## Here you can see that all the Null values has been removed.

The empty array shows that no null value is there in X[0] which was there in the above cells.


In [132]:
X = pd.DataFrame(X)

In [133]:
X_null = np.where(X[0].isnull())[0]

In [134]:
X_null

array([], dtype=int64)

# Now we train our model as we have required Data.

In [160]:
from sklearn.model_selection import train_test_split;
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1);

In [166]:
X.shape


(1448, 3)

## Applying SVR in our Model



In [162]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(x_train, np.ravel(y_train));

In [163]:
y_pred = regressor.predict(x_test);

In [164]:
x_test.shape

(290, 3)

In [165]:
y_pred.shape

(290,)

In [141]:
y_test.shape

(290, 1)

In [142]:
y_pred.shape

(290,)

In [143]:
y_test=np.ravel(y_test);
y_pred=np.ravel(y_pred);

In [144]:
ac=y_test-y_pred

In [145]:
ac

array([ 5.63056447e+00, -7.14815614e+01, -6.73967346e+01, -9.02153923e+01,
        8.21947260e+01, -1.52855457e+01, -3.05953355e+01,  6.31672865e+01,
       -2.04558581e+02,  7.52393810e+01,  8.39709650e+01, -5.29701468e+01,
       -1.25050822e+01, -4.16701465e+01,  1.00586571e+02, -7.09553810e+01,
       -1.78250707e+01,  5.63288933e+01,  1.18395571e+02, -5.42163360e+01,
        1.83858622e+02, -1.26450304e+02,  5.53717125e+01, -1.33000264e+01,
        6.29957688e+00,  1.00952297e+01, -7.58774741e+01,  7.35948044e+01,
        9.20781884e+01,  2.12884557e+01,  3.64376175e+01,  5.49200636e+01,
        1.07835670e+02, -1.54928372e+01, -9.68132746e+00,  4.01525683e+01,
       -1.10009286e+01, -8.94569688e+01,  9.66186989e+00, -1.18489224e+01,
        8.60542120e+01, -4.75641924e+01,  7.71463831e+01,  5.93187635e+01,
       -2.84204086e+01, -5.29433767e+01, -5.42724860e+01, -4.58531836e+01,
        4.54790021e+01,  1.55490537e+02,  1.72492709e+01, -3.66972628e+01,
       -9.33002061e+01,  

In [146]:
sum=np.zeros(218);
for i in range(0,218,1):
    sum[i]=ac[i]/218;

In [147]:
div=y_test+y_pred

In [148]:
per=ac/div;

In [149]:

per*=100

In [150]:
per

array([  1.2786002 , -26.9252452 , -26.18398974, -39.18738508,
        12.5717441 ,  -1.90287822,  -8.6282397 ,  10.44376158,
       -37.0202523 ,  11.11757672,  18.91114283,  -5.90545259,
        -2.01530698, -14.38537834,  13.49406483, -27.61389183,
        -4.59616257,  12.58265106,  18.74520903, -19.48711452,
        25.53090655, -10.31026722,  10.43512262,  -3.39893318,
         1.16292634,   1.4891811 , -30.85987212,  12.29849021,
        17.1173926 ,   3.38604499,   7.72699835,  11.36873206,
        16.4342475 ,  -2.002971  ,  -2.41020102,   7.04619623,
        -3.51466326, -37.99291618,   1.3375827 ,  -3.42604   ,
        17.21270868, -17.01369262,  13.60957763,  10.85070414,
        -8.76036398, -19.98290253, -20.08065519,  -5.42093882,
         7.37671584,  29.5323347 ,   2.61848225, -12.53761736,
       -17.62708668,  12.16118871,  14.30798624,  11.810037  ,
       -11.09476188, -37.37952785,  -1.6521606 ,   9.76976825,
       -13.24279924, -27.87661137,   0.90713337,   7.77

In [154]:
ans=0;
for i in range(0,290,1):
    ans+=abs(per[i]);

In [155]:
ans/=218


In [156]:
ans

16.655500612322324