# Importing Libraries


In [1]:
import pandas as pd;
import numpy as np;

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [3]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,-2:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [4]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [5]:
new_df['Year'] = new_df['Date'].dt.year

In [6]:
new_df = new_df.set_index(['Year'])

In [7]:
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [8]:
ds_delhi_16

City       Date    AQI AQI_Bucket
Year                                    
2016  Delhi 2016-01-01  463.0     Severe
2016  Delhi 2016-01-02  465.0     Severe
2016  Delhi 2016-01-03  426.0     Severe
2016  Delhi 2016-01-04  496.0     Severe
2016  Delhi 2016-01-05  528.0     Severe
...     ...        ...    ...        ...
2016  Delhi 2016-12-27  319.0  Very Poor
2016  Delhi 2016-12-28  455.0     Severe
2016  Delhi 2016-12-29  524.0     Severe
2016  Delhi 2016-12-30  381.0  Very Poor
2016  Delhi 2016-12-31  338.0  Very Poor

[366 rows x 4 columns]

In [9]:
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

In [10]:
x_17=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [11]:
x_16=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [12]:
x_18=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [13]:
x_18

array([[462., 439., 405., 394.],
       [439., 405., 394., 398.],
       [405., 394., 398., 403.],
       ...,
       [405., 458., 413., 420.],
       [458., 413., 420., 484.],
       [413., 420., 484., 509.]])

In [14]:
x_19=np.zeros((362,4));
point=0;
count=0;
for i in range(0,362,1):
    for j in range(0,4,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [ ]:
x_16.shape

In [ ]:
x_17.shape

In [15]:
ds_3=np.concatenate((x_16,x_17,x_18),axis=0);

In [16]:
ds_3.shape

(1086, 4)

In [17]:
ds_3= pd.DataFrame(ds_3, columns = ['last 3rd','last 2nd','last 1st','present'])

In [36]:
ds_3.to_csv('previous_3.csv');

In [18]:
X=ds_3.iloc[:,[0,1,2]].values;
Y=ds_3.iloc[:,[-1]].values;

In [19]:
X

array([[463., 465., 426.],
       [465., 426., 496.],
       [426., 496., 528.],
       ...,
       [405., 458., 413.],
       [458., 413., 420.],
       [413., 420., 484.]])

In [20]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(X);
X=ds_imputer.transform(X);

In [21]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(Y);
Y=ds_imputer.transform(Y);

In [35]:
X

array([[463., 465., 426.],
       [465., 426., 496.],
       [426., 496., 528.],
       ...,
       [405., 458., 413.],
       [458., 413., 420.],
       [413., 420., 484.]])

In [22]:
Y

array([[496.],
       [528.],
       [538.],
       ...,
       [420.],
       [484.],
       [509.]])

In [23]:
from sklearn.model_selection import train_test_split;
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1);

In [26]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(x_train, np.ravel(y_train));

In [27]:
y_pred=regressor.predict(x_test);

In [28]:
y_pred.shape

(218,)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix;

In [30]:
ac=y_test-y_pred

In [34]:
ac

array([[ -36.36090357,  -37.57030011,  -31.47264273, ..., -233.95916259,
         -16.29379354,  -82.7695177 ],
       [ 150.63909643,  149.42969989,  155.52735727, ...,  -46.95916259,
         170.70620646,  104.2304823 ],
       [ -82.36090357,  -83.57030011,  -77.47264273, ..., -279.95916259,
         -62.29379354, -128.7695177 ],
       ...,
       [ 213.63909643,  212.42969989,  218.52735727, ...,   16.04083741,
         233.70620646,  167.2304823 ],
       [-100.36090357, -101.57030011,  -95.47264273, ..., -297.95916259,
         -80.29379354, -146.7695177 ],
       [  35.63909643,   34.42969989,   40.52735727, ..., -161.95916259,
          55.70620646,  -10.7695177 ]])

In [31]:
y_test=np.ravel(y_test);
y_pred=np.ravel(y_pred);

In [33]:
sum=np.zeros(218);
for i in range(0,218,1):
    sum[i]=ac[i]/218;

ValueError: setting an array element with a sequence.

In [ ]:
per

In [ ]:
div=y_test+y_pred

In [ ]:
per=ac/div;

In [ ]:
per*=100

In [ ]:
ans=0;
for i in range(0,218,1):
    ans+=abs(per[i]);

In [ ]:
ans/=218

In [ ]:
ans

In [ ]:
aqi_20

In [ ]:
aqi_20.shape

In [ ]:
ds_4=np.zeros((183,4));

In [ ]:
ds_4[0][0]=420;
ds_4[0][1]=484;
ds_4[0][2]=509;
ds_4[0][3]=regressor.predict([[420,484,509]]);

In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
for i in range(1,183,1):
    for j in range(0,4,1):
        if(j == 3):
            print(" - ",regressor.predict([[ds_4[i][0], ds_4[i][1], ds_4[i][2]]]));
            ds_4[i][j]=regressor.predict([[ds_4[i][0], ds_4[i][1], ds_4[i][2]]]);
        if(j < 3):
            ds_4[i][j]=ds_4[i-1][j+1];

In [ ]:
print(ds_4)

In [ ]:
regressor.predict([[484, 509, 560]])