# Importing Libraries


In [3]:
pip install cufflinks


  Using cached cufflinks-0.17.3.tar.gz (81 kB)
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Note: you may need to restart the kernel to use updated packages.
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68724 sha256=227e1b0974b1db5ea9802bc42473a2fd2cf2d4f87d84d5f9f7d9afd60b4e1f64
  Stored in directory: c:\users\payus\appdata\local\pip\cache\wheels\6b\76\62\6da97734911ffcbdd559fd1a3f28526321f0ae699182a23866
Successfully built cufflinks


In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [3]:
ds_1=pd.read_csv('city_day.csv');

In [4]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,7:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [5]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [6]:
new_df['Year'] = new_df['Date'].dt.year

In [7]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [8]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [9]:
ds_delhi_16

City       Date    NH3    CO    SO2      O3  Benzene  Toluene  Xylene  \
Year                                                                           
2016  Delhi 2016-01-01  79.87  2.42  23.57  108.14     5.81    16.30     0.0   
2016  Delhi 2016-01-02  65.11  2.15  23.33   90.45     5.79    17.65     NaN   
2016  Delhi 2016-01-03  66.40  2.39  19.94   97.03     5.33    10.78     NaN   
2016  Delhi 2016-01-04  73.73  2.97  27.90   91.20     7.12    19.01     NaN   
2016  Delhi 2016-01-05  78.22  2.85  30.24  131.40     6.45    21.32     NaN   
...     ...        ...    ...   ...    ...     ...      ...      ...     ...   
2016  Delhi 2016-12-27  47.88  0.94  24.51   36.90     6.13    11.06     NaN   
2016  Delhi 2016-12-28  60.40  1.61  26.10   40.19     7.04    16.43     NaN   
2016  Delhi 2016-12-29  88.44  1.30  21.60   55.09     7.29    18.01     NaN   
2016  Delhi 2016-12-30  54.58  0.96  23.47   43.97     6.93    12.43     NaN   
2016  Delhi 2016-12-31  52.53  1.14  23.82   42.84     8.03    17.16     NaN   

        AQI AQI_Bucket  
Year                    
2016  463.0     Severe  
2016  465.0     Severe  
2016  426.0     Severe  
2016  496.0     Severe  
2016  528.0     Severe  
...     ...        ...  
2016  319.0  Very Poor  
2016  455.0     Severe  
2016  524.0     Severe  
2016  381.0  Very Poor  
2016  338.0  Very Poor  

[366 rows x 11 columns]

# AQI DATAFRAMES

In [10]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [11]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [12]:
aqi_level_17

City       Date    NH3    CO    SO2     O3  Benzene  Toluene  Xylene  \
Year                                                                          
2017  Delhi 2017-01-01  55.92  1.31  25.13  50.03     8.39    19.94     NaN   
2017  Delhi 2017-01-02  66.57  1.47  22.29  47.86     8.96    18.92     NaN   
2017  Delhi 2017-01-03  58.97  1.28  25.33  42.90     7.65    13.96     NaN   
2017  Delhi 2017-01-04  68.53  1.55  23.11  41.13     7.26    16.51     NaN   
2017  Delhi 2017-01-05  61.04  1.24  25.15  41.95     5.73    12.89     NaN   
...     ...        ...    ...   ...    ...    ...      ...      ...     ...   
2017  Delhi 2017-12-27  71.71  1.69  23.17  58.98     5.95    18.27    0.03   
2017  Delhi 2017-12-28  79.07  1.86  25.51  66.00     6.36    23.66    0.00   
2017  Delhi 2017-12-29  68.22  1.70  25.54  61.36     5.35    19.38    0.77   
2017  Delhi 2017-12-30  75.04  1.96  21.01  61.73     6.96    25.19    1.18   
2017  Delhi 2017-12-31  83.55  1.95  17.97  76.45     7.01    21.12    0.35   

        AQI AQI_Bucket  
Year                    
2017  332.0  Very Poor  
2017  384.0  Very Poor  
2017  373.0  Very Poor  
2017  439.0     Severe  
2017  318.0  Very Poor  
...     ...        ...  
2017  379.0  Very Poor  
2017  398.0  Very Poor  
2017  399.0  Very Poor  
2017  421.0     Severe  
2017  451.0     Severe  

[365 rows x 11 columns]

In [13]:
aqi_level_17.iloc[:,2],

(Year
 2017    55.92
 2017    66.57
 2017    58.97
 2017    68.53
 2017    61.04
         ...  
 2017    71.71
 2017    79.07
 2017    68.22
 2017    75.04
 2017    83.55
 Name: NH3, Length: 365, dtype: float64,)

In [14]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NH3",
        title_standoff = 25)
fig.update_layout(title_text="NH3 2017")

fig.show()

In [15]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NH3",
        title_standoff = 25)
fig.update_layout(title_text="NH3 2018")

fig.show()

In [17]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NH3",
        title_standoff = 25)
fig.update_layout(title_text="NH3 2019")

fig.show()

In [18]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,2],
                         x = aqi_level_20.iloc[:,1]),
                         row = 2,col = 3)
fig.update_layout(title_text="NH3 IN DIFFERENT YEARS", height=700)
fig.show()


In [24]:
fig = px.scatter_3d(aqi_level_20, x= "PM10", y="Date", z="AQI_Bucket")
fig.show()

In [19]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [20]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [21]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [22]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [23]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [24]:
x_18

array([[73.16, 55.61, 50.81, 55.17, 51.36, 63.78],
       [55.61, 50.81, 55.17, 51.36, 63.78, 50.09],
       [50.81, 55.17, 51.36, 63.78, 50.09, 47.52],
       ...,
       [67.29, 65.75, 57.34, 50.38, 56.6 , 55.46],
       [65.75, 57.34, 50.38, 56.6 , 55.46, 51.53],
       [57.34, 50.38, 56.6 , 55.46, 51.53, 57.55]])

In [25]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [26]:
x_16.shape

(359, 6)

In [27]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [28]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [29]:
ds_5.shape

(1795, 6)

In [30]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [31]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0        33.85     31.83     69.55    130.36    122.88   134.97
1        31.83     69.55    130.36    122.88    134.97   134.82
2        69.55    130.36    122.88    134.97    134.82   138.13
3       130.36    122.88    134.97    134.82    138.13   140.60
4       122.88    134.97    134.82    138.13    140.60   134.06
...        ...       ...       ...       ...       ...      ...
1790     62.14     57.51     53.04     53.30     48.52    51.83
1791     57.51     53.04     53.30     48.52     51.83    52.64
1792     53.04     53.30     48.52     51.83     52.64    50.47
1793     53.30     48.52     51.83     52.64     50.47    49.61
1794     48.52     51.83     52.64     50.47     49.61    50.75

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [32]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [33]:
svr_X

array([[ 33.85,  31.83,  69.55, 130.36, 122.88],
       [ 31.83,  69.55, 130.36, 122.88, 134.97],
       [ 69.55, 130.36, 122.88, 134.97, 134.82],
       ...,
       [ 53.04,  53.3 ,  48.52,  51.83,  52.64],
       [ 53.3 ,  48.52,  51.83,  52.64,  50.47],
       [ 48.52,  51.83,  52.64,  50.47,  49.61]])

### Step 2 :Removing the null values 

In [34]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [35]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [36]:
svr_X

array([[ 33.85,  31.83,  69.55, 130.36, 122.88],
       [ 31.83,  69.55, 130.36, 122.88, 134.97],
       [ 69.55, 130.36, 122.88, 134.97, 134.82],
       ...,
       [ 53.04,  53.3 ,  48.52,  51.83,  52.64],
       [ 53.3 ,  48.52,  51.83,  52.64,  50.47],
       [ 48.52,  51.83,  52.64,  50.47,  49.61]])

In [37]:
svr_Y

array([[134.97],
       [134.82],
       [138.13],
       ...,
       [ 50.47],
       [ 49.61],
       [ 50.75]])

### Step 3: Test - Train - Split

In [38]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [39]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [40]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [41]:
svr_y_pred.shape


(359,)

In [42]:
svr_y_test.shape

(359, 1)

In [43]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [44]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [45]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.6934415751380505

In [46]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.6938274207748725

In [47]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

0.15249795838514013

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [48]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-48-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [49]:
xg_X.shape

(365, 5)

In [50]:
xg_X[205,:]

array([37.05, 38.44, 28.73, 39.46, 37.17])

In [51]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [52]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [53]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [54]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [55]:
svr_x_train

array([[38.01, 38.61, 44.85, 44.57, 45.99],
       [41.49, 57.73, 77.11, 86.87, 50.54],
       [28.42, 33.83, 39.17, 46.24, 47.95],
       ...,
       [66.51, 63.25, 63.15, 51.07, 43.08],
       [38.16, 36.07, 31.88, 25.74, 32.56],
       [77.11, 86.87, 50.54, 48.27, 46.26]])

In [56]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [57]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [58]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.16794992941612572

In [59]:
xg_pred.shape

(365,)

In [60]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.5274427773056203

### Visualization in XgBoost 

In [61]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [62]:
df_xg

Predicted  Actual
0    46.113007   56.85
1    58.813351   58.26
2    56.823601   53.02
3    63.402969   53.46
4    63.394272   47.94
..         ...     ...
178  30.979170   31.43
179  28.365988   29.27
180  25.427597   27.97
181  24.125937   28.48
182  31.146536   29.06

[183 rows x 2 columns]

In [63]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 NH3 Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [64]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [65]:
x=df_xg.iloc[85:,0]-x

In [66]:
np.mean(x)

29.869183673469383

In [67]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [68]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [69]:
t=(a-b)/a

In [70]:
t

0.12109932267156423

### 2.) Decision Tree Model

In [89]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [90]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

NameError: name 'x_test' is not defined

### 3.) Random Forest Classification

In [91]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

In [92]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

NameError: name 'x_test' is not defined

In [93]:
aqi_16.shape

(366,)

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])