# Importing Libraries


In [1]:
pip install cufflinks


Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [4]:
ds_1=pd.read_csv('city_day.csv');

In [11]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,10:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [12]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [13]:
new_df['Year'] = new_df['Date'].dt.year

In [14]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [15]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [16]:
ds_delhi_16

City       Date      O3  Benzene  Toluene  Xylene    AQI AQI_Bucket
Year                                                                      
2016  Delhi 2016-01-01  108.14     5.81    16.30     0.0  463.0     Severe
2016  Delhi 2016-01-02   90.45     5.79    17.65     NaN  465.0     Severe
2016  Delhi 2016-01-03   97.03     5.33    10.78     NaN  426.0     Severe
2016  Delhi 2016-01-04   91.20     7.12    19.01     NaN  496.0     Severe
2016  Delhi 2016-01-05  131.40     6.45    21.32     NaN  528.0     Severe
...     ...        ...     ...      ...      ...     ...    ...        ...
2016  Delhi 2016-12-27   36.90     6.13    11.06     NaN  319.0  Very Poor
2016  Delhi 2016-12-28   40.19     7.04    16.43     NaN  455.0     Severe
2016  Delhi 2016-12-29   55.09     7.29    18.01     NaN  524.0     Severe
2016  Delhi 2016-12-30   43.97     6.93    12.43     NaN  381.0  Very Poor
2016  Delhi 2016-12-31   42.84     8.03    17.16     NaN  338.0  Very Poor

[366 rows x 8 columns]

# AQI DATAFRAMES

In [17]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [18]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [19]:
aqi_level_17

City       Date     O3  Benzene  Toluene  Xylene    AQI AQI_Bucket
Year                                                                     
2017  Delhi 2017-01-01  50.03     8.39    19.94     NaN  332.0  Very Poor
2017  Delhi 2017-01-02  47.86     8.96    18.92     NaN  384.0  Very Poor
2017  Delhi 2017-01-03  42.90     7.65    13.96     NaN  373.0  Very Poor
2017  Delhi 2017-01-04  41.13     7.26    16.51     NaN  439.0     Severe
2017  Delhi 2017-01-05  41.95     5.73    12.89     NaN  318.0  Very Poor
...     ...        ...    ...      ...      ...     ...    ...        ...
2017  Delhi 2017-12-27  58.98     5.95    18.27    0.03  379.0  Very Poor
2017  Delhi 2017-12-28  66.00     6.36    23.66    0.00  398.0  Very Poor
2017  Delhi 2017-12-29  61.36     5.35    19.38    0.77  399.0  Very Poor
2017  Delhi 2017-12-30  61.73     6.96    25.19    1.18  421.0     Severe
2017  Delhi 2017-12-31  76.45     7.01    21.12    0.35  451.0     Severe

[365 rows x 8 columns]

In [20]:
aqi_level_17.iloc[:,2],

(Year
 2017    50.03
 2017    47.86
 2017    42.90
 2017    41.13
 2017    41.95
         ...  
 2017    58.98
 2017    66.00
 2017    61.36
 2017    61.73
 2017    76.45
 Name: O3, Length: 365, dtype: float64,)

In [21]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2017")

fig.show()

In [22]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2018")

fig.show()

In [23]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "NO",
        title_standoff = 25)
fig.update_layout(title_text="NO 2019")

fig.show()

In [24]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)
fig.add_trace(go.Scatter(name="2020",
                         mode = "lines+markers", 
                         y = aqi_level_20.iloc[:,2],
                         x = aqi_level_20.iloc[:,1]),
                         row = 2,col = 3)
fig.update_layout(title_text="NO IN DIFFERENT YEARS", height=700)
fig.show()


In [25]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [26]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [27]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [28]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [29]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [30]:
x_18

array([[68.75, 68.68, 54.94, 66.31, 48.57, 39.65],
       [68.68, 54.94, 66.31, 48.57, 39.65, 57.39],
       [54.94, 66.31, 48.57, 39.65, 57.39, 54.55],
       ...,
       [50.65, 43.25, 36.37, 39.09, 40.96, 37.38],
       [43.25, 36.37, 39.09, 40.96, 37.38, 39.29],
       [36.37, 39.09, 40.96, 37.38, 39.29, 42.87]])

In [31]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [32]:
x_16.shape

(359, 6)

In [33]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [34]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [35]:
ds_5.shape

(1795, 6)

In [36]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [37]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0        41.68     29.97     19.71     25.36     23.20    26.83
1        29.97     19.71     25.36     23.20     26.83    28.96
2        19.71     25.36     23.20     26.83     28.96    30.51
3        25.36     23.20     26.83     28.96     30.51    32.94
4        23.20     26.83     28.96     30.51     32.94    34.12
...        ...       ...       ...       ...       ...      ...
1790     23.62     21.48     23.80     28.17     21.13    25.73
1791     21.48     23.80     28.17     21.13     25.73    27.55
1792     23.80     28.17     21.13     25.73     27.55    27.92
1793     28.17     21.13     25.73     27.55     27.92    35.11
1794     21.13     25.73     27.55     27.92     35.11    26.44

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [38]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [39]:
svr_X

array([[41.68, 29.97, 19.71, 25.36, 23.2 ],
       [29.97, 19.71, 25.36, 23.2 , 26.83],
       [19.71, 25.36, 23.2 , 26.83, 28.96],
       ...,
       [23.8 , 28.17, 21.13, 25.73, 27.55],
       [28.17, 21.13, 25.73, 27.55, 27.92],
       [21.13, 25.73, 27.55, 27.92, 35.11]])

### Step 2 :Removing the null values 

In [40]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [41]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [42]:
svr_X

array([[41.68, 29.97, 19.71, 25.36, 23.2 ],
       [29.97, 19.71, 25.36, 23.2 , 26.83],
       [19.71, 25.36, 23.2 , 26.83, 28.96],
       ...,
       [23.8 , 28.17, 21.13, 25.73, 27.55],
       [28.17, 21.13, 25.73, 27.55, 27.92],
       [21.13, 25.73, 27.55, 27.92, 35.11]])

In [43]:
svr_Y

array([[26.83],
       [28.96],
       [30.51],
       ...,
       [27.92],
       [35.11],
       [26.44]])

### Step 3: Test - Train - Split

In [44]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [45]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [46]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [47]:
svr_y_pred.shape


(359,)

In [48]:
svr_y_test.shape

(359, 1)

In [49]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [50]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [51]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.7452919301684537

In [52]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.745890773913044

In [53]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

0.1580181830881043

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [54]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-54-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [55]:
xg_X.shape

(365, 5)

In [56]:
xg_X[205,:]

array([45.9 , 65.42,   nan, 21.39, 22.78])

In [57]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [58]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [59]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [60]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [61]:
svr_x_train

array([[50.16, 59.09, 59.48, 57.57, 57.48],
       [50.26, 68.58, 90.07, 66.07, 38.75],
       [33.55, 33.03, 37.03, 43.29, 43.36],
       ...,
       [43.18, 41.49, 68.33, 48.67, 42.04],
       [38.73, 44.9 , 40.43, 56.61, 64.07],
       [90.07, 66.07, 38.75, 46.28, 42.19]])

In [62]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [63]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [64]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.175837966743171

In [65]:
xg_pred.shape

(365,)

In [66]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.5046225351808067

### Visualization in XgBoost 

In [67]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [68]:
df_xg

Predicted  Actual
0    65.312576   39.58
1    54.656467   36.50
2    74.958656   27.82
3    40.264183   29.94
4    63.137711   30.21
..         ...     ...
178  34.290230   18.88
179  39.499363   18.05
180  45.271671   26.61
181  48.759586   37.29
182  55.727356   29.73

[183 rows x 2 columns]

In [69]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 NO Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [70]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [71]:
x=df_xg.iloc[85:,0]-x

In [72]:
np.mean(x)

46.56724489795916

In [73]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [74]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [75]:
t=(a-b)/a

In [83]:
a

51.28796657250852

In [84]:
b

46.56724489795916

In [76]:
t

0.09204345561010739

### 2.) Decision Tree Model

In [77]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

NameError: name 'x_train' is not defined

### Error In Decision Tree Model

In [ ]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

### 3.) Random Forest Classification

In [ ]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

In [ ]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

In [ ]:
aqi_16.shape

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [78]:
xg_pred_2020=xg_regressor.predict(aqis)

NameError: name 'aqis' is not defined

In [79]:
xg_pred

array([65.31258 , 54.656467, 74.95866 , 40.264183, 63.13771 , 60.74551 ,
       58.63207 , 54.871838, 69.45786 , 62.4461  , 58.5369  , 63.05258 ,
       69.0811  , 60.324528, 32.381935, 39.730072, 54.610474, 66.42772 ,
       76.307465, 69.244286, 33.226692, 49.214027, 51.45676 , 49.854794,
       51.523006, 59.550507, 63.52192 , 60.48237 , 65.60996 , 66.320045,
       50.318123, 52.740032, 53.522366, 55.989906, 51.868523, 73.80794 ,
       60.693443, 54.725002, 38.98879 , 63.63748 , 59.49029 , 52.721863,
       61.50613 , 70.48278 , 43.398643, 43.68255 , 56.55893 , 45.017284,
       47.016964, 64.70947 , 48.84139 , 49.947853, 47.7775  , 71.48867 ,
       65.908875, 70.51735 , 49.756252, 58.401627, 58.020348, 59.832973,
       55.822193, 59.05723 , 60.83421 , 61.976883, 45.229504, 48.8546  ,
       53.619312, 44.60189 , 48.152695, 53.77058 , 35.46734 , 34.748474,
       43.23671 , 38.38358 , 45.725174, 44.63078 , 46.994648, 39.03068 ,
       40.100136, 63.796486, 35.202644, 44.75947 , 

In [80]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

<ipython-input-80-19bebabef62e>:1: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



NameError: name 'xg_pred_2020' is not defined

In [81]:
xg_regressor.fit(x_train, np.ravel(y_train));

NameError: name 'x_train' is not defined

In [82]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

NameError: name 'xg_pred_2020' is not defined

<Figure size 432x288 with 0 Axes>

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])