# Importing Libraries


In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import cufflinks as cf
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

from plotly.offline import download_plotlyjs, init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()

## Dataset Cleaning

In [2]:
ds_1=pd.read_csv('city_day.csv');

In [3]:
new_df = pd.concat([ds_1.iloc[:,0:2],ds_1.iloc[:,2:]],axis = 1)

new_df = new_df[new_df['City'] == 'Delhi']

In [4]:
new_df['Date'] = pd.to_datetime(new_df['Date'])

In [5]:
new_df['Year'] = new_df['Date'].dt.year

In [6]:
new_df = new_df.set_index(['Year'])

## Making dataframes

In [7]:
ds_delhi_15=new_df.loc['2015'];
ds_delhi_16=new_df.loc['2016'];
ds_delhi_17=new_df.loc['2017'];
ds_delhi_18=new_df.loc['2018'];
ds_delhi_19=new_df.loc['2019'];
ds_delhi_20=new_df.loc['2020'];

In [8]:
ds_delhi_16

City       Date   PM2.5    PM10      NO     NO2     NOx    NH3    CO  \
Year                                                                          
2016  Delhi 2016-01-01  295.71  476.09   86.62   94.04  131.36  79.87  2.42   
2016  Delhi 2016-01-02  239.21  395.29   69.42   81.22  126.63  65.11  2.15   
2016  Delhi 2016-01-03  270.10  484.82   54.41   76.67  101.63  66.40  2.39   
2016  Delhi 2016-01-04  339.80  586.20  124.31  133.95  164.05  73.73  2.97   
2016  Delhi 2016-01-05  318.10  535.30  106.93  118.81  159.99  78.22  2.85   
...     ...        ...     ...     ...     ...     ...     ...    ...   ...   
2016  Delhi 2016-12-27  213.20  395.37  114.55   93.45   56.14  47.88  0.94   
2016  Delhi 2016-12-28  273.82  515.41  192.34  129.41   67.59  60.40  1.61   
2016  Delhi 2016-12-29  339.96  535.68  103.69  108.76   33.56  88.44  1.30   
2016  Delhi 2016-12-30  231.10  368.90   30.99   62.46   33.89  54.58  0.96   
2016  Delhi 2016-12-31  211.16  353.61   40.62   56.66   44.59  52.53  1.14   

        SO2      O3  Benzene  Toluene  Xylene    AQI AQI_Bucket  
Year                                                             
2016  23.57  108.14     5.81    16.30     0.0  463.0     Severe  
2016  23.33   90.45     5.79    17.65     NaN  465.0     Severe  
2016  19.94   97.03     5.33    10.78     NaN  426.0     Severe  
2016  27.90   91.20     7.12    19.01     NaN  496.0     Severe  
2016  30.24  131.40     6.45    21.32     NaN  528.0     Severe  
...     ...     ...      ...      ...     ...    ...        ...  
2016  24.51   36.90     6.13    11.06     NaN  319.0  Very Poor  
2016  26.10   40.19     7.04    16.43     NaN  455.0     Severe  
2016  21.60   55.09     7.29    18.01     NaN  524.0     Severe  
2016  23.47   43.97     6.93    12.43     NaN  381.0  Very Poor  
2016  23.82   42.84     8.03    17.16     NaN  338.0  Very Poor  

[366 rows x 16 columns]

# AQI DATAFRAMES

In [9]:
aqi_15 = ds_delhi_15.iloc[:,2].values;
aqi_16 = ds_delhi_16.iloc[:,2].values;
aqi_17 = ds_delhi_17.iloc[:,2].values;
aqi_18 = ds_delhi_18.iloc[:,2].values;
aqi_19 = ds_delhi_19.iloc[:,2].values;
aqi_20 = ds_delhi_20.iloc[:,2].values;

# Visualization Of The Data

In [10]:
aqi_level_15 = new_df.loc['2015']
aqi_level_16 = new_df.loc['2016']
aqi_level_17 = new_df.loc['2017']
aqi_level_18 = new_df.loc['2018']
aqi_level_19 = new_df.loc['2019']
aqi_level_20 = new_df.loc['2020']

In [11]:
aqi_level_17

City       Date   PM2.5    PM10      NO    NO2    NOx    NH3    CO  \
Year                                                                        
2017  Delhi 2017-01-01  191.50  402.31  103.24  66.19  55.29  55.92  1.31   
2017  Delhi 2017-01-02  247.79  440.18  221.03  95.55  80.85  66.57  1.47   
2017  Delhi 2017-01-03  255.33  390.67  155.29  90.79  53.89  58.97  1.28   
2017  Delhi 2017-01-04  248.01  341.15  186.07  91.07  71.88  68.53  1.55   
2017  Delhi 2017-01-05  215.42  352.83  141.69  87.15  64.41  61.04  1.24   
...     ...        ...     ...     ...     ...    ...    ...    ...   ...   
2017  Delhi 2017-12-27  224.27  317.87   58.71  65.61   9.76  71.71  1.69   
2017  Delhi 2017-12-28  249.17  362.39   80.57  70.25  11.62  79.07  1.86   
2017  Delhi 2017-12-29  227.28  347.63   70.60  59.70  10.69  68.22  1.70   
2017  Delhi 2017-12-30  273.56  401.15   69.31  60.40  15.32  75.04  1.96   
2017  Delhi 2017-12-31  306.17  445.58   83.77  66.97  23.13  83.55  1.95   

        SO2     O3  Benzene  Toluene  Xylene    AQI AQI_Bucket  
Year                                                            
2017  25.13  50.03     8.39    19.94     NaN  332.0  Very Poor  
2017  22.29  47.86     8.96    18.92     NaN  384.0  Very Poor  
2017  25.33  42.90     7.65    13.96     NaN  373.0  Very Poor  
2017  23.11  41.13     7.26    16.51     NaN  439.0     Severe  
2017  25.15  41.95     5.73    12.89     NaN  318.0  Very Poor  
...     ...    ...      ...      ...     ...    ...        ...  
2017  23.17  58.98     5.95    18.27    0.03  379.0  Very Poor  
2017  25.51  66.00     6.36    23.66    0.00  398.0  Very Poor  
2017  25.54  61.36     5.35    19.38    0.77  399.0  Very Poor  
2017  21.01  61.73     6.96    25.19    1.18  421.0     Severe  
2017  17.97  76.45     7.01    21.12    0.35  451.0     Severe  

[365 rows x 16 columns]

In [12]:
aqi_level_17.iloc[:,2],

(Year
 2017    191.50
 2017    247.79
 2017    255.33
 2017    248.01
 2017    215.42
          ...  
 2017    224.27
 2017    249.17
 2017    227.28
 2017    273.56
 2017    306.17
 Name: PM2.5, Length: 365, dtype: float64,)

In [13]:
#2017
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "PM2.5",
        title_standoff = 25)
fig.update_layout(title_text="PM2.5 2017")

fig.show()

In [14]:
#2018
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "PM2.5",
        title_standoff = 25)
fig.update_layout(title_text="PM2.5 2018")

fig.show()

In [15]:
#2019
fig = go.Figure(go.Scatter(
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]))
fig.update_xaxes(
        tickangle = 90,
        title_text = "Month",
        title_font = {"size": 20},
        title_standoff = 25)

fig.update_yaxes(
        title_text = "PM2.5",
        title_standoff = 25)
fig.update_layout(title_text="PM2.5 2019")

fig.show()

In [69]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3,subplot_titles=("2015","2016", "2017", "2018","2019"))
fig.add_trace(
    go.Scatter(
    name ="2016",
    mode = "lines+markers",
    y = aqi_level_16.iloc[:,2],
    x = aqi_level_16.iloc[:,1]),
    row = 1 ,col =2)


fig.add_trace(go.Scatter(
    name ="2017",
    mode = "lines+markers",
    y = aqi_level_17.iloc[:,2],
    x = aqi_level_17.iloc[:,1]),
    row=1, col=3
)

    
    


fig.add_trace(go.Scatter(
    name ="2018",
    mode = "lines+markers",
    y = aqi_level_18.iloc[:,2],
    x = aqi_level_18.iloc[:,1]),
    row=2, col=1
)

fig.add_trace(go.Scatter(
    name ="2019",
    mode = "lines+markers",
    y = aqi_level_19.iloc[:,2],
    x = aqi_level_19.iloc[:,1]),
    row=2, col=2
)

fig.add_trace(go.Scatter(
    name ="2015",
    mode = "lines+markers",
    y = aqi_level_15.iloc[:,2],
    x = aqi_level_15.iloc[:,1]),
    row=1, col=1
)

fig.update_layout(title_text="PM2.5 IN DIFFERENT YEARS", height=700)
fig.show()


In [17]:
fig = px.scatter_3d(aqi_level_20, x= "PM2.5", y="Date", z="AQI_Bucket")
fig.show()

In [18]:
aqi_15.shape

(365,)

# Making arrays for last 5 days and present data

In [19]:
x_15=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_15[i][j]= aqi_15[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [20]:
x_17=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_17[i][j]= aqi_17[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [21]:
x_16=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_16[i][j]= aqi_16[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [22]:
x_18=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_18[i][j]= aqi_18[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 359):
        break;

In [23]:
x_18

array([[303.41, 277.48, 217.01, 248.54, 240.42, 252.57],
       [277.48, 217.01, 248.54, 240.42, 252.57, 191.66],
       [217.01, 248.54, 240.42, 252.57, 191.66, 152.98],
       ...,
       [401.58, 378.68, 268.2 , 241.  , 290.1 , 249.23],
       [378.68, 268.2 , 241.  , 290.1 , 249.23, 248.12],
       [268.2 , 241.  , 290.1 , 249.23, 248.12, 336.42]])

In [24]:
x_19=np.zeros((359,6));
point=0;
count=0;
for i in range(0,359,1):
    for j in range(0,6,1):
        x_19[i][j]= aqi_19[point];
        point += 1;
    count += 1;
    point = count;
    if (count == 362):
        break;

In [25]:
x_16.shape

(359, 6)

In [26]:
x_17.shape

(359, 6)

# Making a single dataframe of above arrays


Gathering All the data in one dataframe.

In [27]:
ds_5=np.concatenate((x_15,x_16,x_17,x_18,x_19),axis=0);

In [28]:
ds_5.shape

(1795, 6)

In [29]:
ds_5= pd.DataFrame(ds_5, columns = ['last 5th','last 4th','last 3rd','last 2nd','last 1st','present'])

In [30]:
ds_5

last 5th  last 4th  last 3rd  last 2nd  last 1st  present
0       313.22    186.18     87.18    151.84    146.60   149.58
1       186.18     87.18    151.84    146.60    149.58   217.87
2        87.18    151.84    146.60    149.58    217.87   229.90
3       151.84    146.60    149.58    217.87    229.90   201.66
4       146.60    149.58    217.87    229.90    201.66   221.02
...        ...       ...       ...       ...       ...      ...
1790    249.87    146.81    171.47    262.69    166.71   196.97
1791    146.81    171.47    262.69    166.71    196.97   240.07
1792    171.47    262.69    166.71    196.97    240.07   275.60
1793    262.69    166.71    196.97    240.07    275.60   326.79
1794    166.71    196.97    240.07    275.60    326.79   333.43

[1795 rows x 6 columns]

# Model Training


### Step 1: Now we start the process of model training by making independent and dependent   variables



In [31]:
svr_X=ds_5.iloc[:,[0,1,2,3,4]].values;
svr_Y=ds_5.iloc[:,[-1]].values;

In [32]:
svr_X

array([[313.22, 186.18,  87.18, 151.84, 146.6 ],
       [186.18,  87.18, 151.84, 146.6 , 149.58],
       [ 87.18, 151.84, 146.6 , 149.58, 217.87],
       ...,
       [171.47, 262.69, 166.71, 196.97, 240.07],
       [262.69, 166.71, 196.97, 240.07, 275.6 ],
       [166.71, 196.97, 240.07, 275.6 , 326.79]])

### Step 2 :Removing the null values 

In [33]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_X);
svr_X=ds_imputer.transform(svr_X);

In [34]:
# from sklearn.impute import SimpleImputer;
# ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(svr_Y);
svr_Y=ds_imputer.transform(svr_Y);

In [35]:
svr_X

array([[313.22, 186.18,  87.18, 151.84, 146.6 ],
       [186.18,  87.18, 151.84, 146.6 , 149.58],
       [ 87.18, 151.84, 146.6 , 149.58, 217.87],
       ...,
       [171.47, 262.69, 166.71, 196.97, 240.07],
       [262.69, 166.71, 196.97, 240.07, 275.6 ],
       [166.71, 196.97, 240.07, 275.6 , 326.79]])

In [36]:
svr_Y

array([[149.58],
       [217.87],
       [229.9 ],
       ...,
       [275.6 ],
       [326.79],
       [333.43]])

### Step 3: Test - Train - Split

In [37]:
from sklearn.model_selection import train_test_split;
svr_x_train,svr_x_test,svr_y_train,svr_y_test=train_test_split(svr_X,svr_Y,test_size=0.2,random_state=1);

### Step 4 : Using Regression Model : Support Vector Regression

In [38]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'linear')
regressor.fit(svr_x_train, svr_y_train);

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [39]:
svr_y_pred=regressor.predict(svr_x_test); #prediction of testing data

In [40]:
svr_y_pred.shape


(359,)

In [41]:
svr_y_test.shape

(359, 1)

In [42]:
df_y =pd.DataFrame(np.concatenate((svr_y_pred.reshape(359,1),svr_y_test),axis =1),columns = ["Predicted","Actual"])

## Comparision Of Predicted AQI and Actual AQI

In [43]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_y.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_y.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "SVR Comparision On Testing Data ",xaxis=dict(
      tickangle=-90
    ))
fig.show()

### Step 5 : Checking accuracy using built-in functions

In [44]:
from sklearn.metrics import r2_score
r2_score(svr_y_test,svr_y_pred)

0.7838526471928431

In [45]:
from sklearn.metrics import explained_variance_score
explained_variance_score(svr_y_test, svr_y_pred)

0.7856128454130351

In [46]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(svr_y_test,svr_y_pred)

0.2558103685290421

## Using Different Model For Comparision

### 1.) XGBOOST Model

In [47]:
xg_X = np.concatenate((aqi_15.reshape(365,1),
                     aqi_16[[range(0,365)]].reshape(365,1),
                     aqi_17.reshape(365,1),
                     aqi_18.reshape(365,1),
                     aqi_19.reshape(365,1)),axis=1)
xg_Y = aqi_19.reshape(365,1);

<ipython-input-47-b3af51a578ec>:2: FutureWarning:

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



In [48]:
xg_X.shape

(365, 5)

In [49]:
xg_X[205,:]

array([46.01, 59.4 , 22.17, 34.7 , 22.79])

In [50]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(xg_X);
xg_X=ds_imputer.transform(xg_X);
ds_imputer.fit(xg_Y);
xg_Y=ds_imputer.transform(xg_Y);

In [51]:
xg_x_train,xg_x_test,xg_y_train,xg_y_test=train_test_split(xg_X,xg_Y,test_size=0.2,random_state=1);

In [52]:
from xgboost import XGBRegressor;
xg_regressor=XGBRegressor();
xg_regressor.fit(svr_x_train, svr_y_train);#training ke liye 5 days ka data upr svr wale se

In [53]:
xg_pred=xg_regressor.predict(xg_X )#ismai jo data dalna hai vo 5 saal wala dalna hai
#orr ye 2020 ki values hai

In [54]:
svr_x_train

array([[ 47.25,  49.09,  74.82, 110.48, 111.95],
       [115.08, 165.76, 230.34, 218.87, 109.18],
       [ 82.5 , 143.31, 173.61, 208.64, 198.26],
       ...,
       [152.33, 153.61, 202.11, 160.79, 130.16],
       [ 37.39,  52.06,  57.52,  61.47,  77.76],
       [230.34, 218.87, 109.18, 134.99, 126.67]])

In [55]:
print(xg_x_test.shape)

(73, 5)


### Error in XgBoost Model

In [56]:
xg_real_pred = xg_regressor.predict(svr_x_test)

In [57]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(xg_real_pred,svr_y_test)

0.27900145470816834

In [58]:
xg_pred.shape

(365,)

In [59]:
from sklearn.metrics import r2_score
r2_score(xg_real_pred, svr_y_test)

0.46763834498673496

### Visualization in XgBoost 

In [60]:
df_xg =pd.DataFrame(np.concatenate((xg_pred[range(0,183)].reshape(183,1),
                                    aqi_20.reshape(183,1)),
                                   axis = 1 ),
                                columns = ["Predicted","Actual"])

In [61]:
df_xg

Predicted  Actual
0    250.469467  372.14
1    291.139465  327.04
2    312.612762  228.90
3    190.597275  220.60
4    227.351166  170.21
..          ...     ...
178   56.912579   39.80
179   63.614773   59.52
180   70.963013   44.86
181   56.755932   39.80
182   68.536453   54.01

[183 rows x 2 columns]

In [62]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

trace1 = go.Scatter(
   
    y=df_xg.iloc[:,-1],
    name="Actual",
    marker=dict(
        color='rgb(34,163,192)'
               )
)
trace2 = go.Scatter(
    y=df_xg.iloc[:,0],
    
    name='Predicted',
    yaxis='y2'

)
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 600, width = 800, title = "2020 PM2.5 Prediction Using XgBoost",xaxis=dict(
      tickangle=-90
    ))
fig.show()

In [63]:
x=df_xg.iloc[85:,0]-df_xg.iloc[85:,-1]

In [64]:
x=df_xg.iloc[85:,0]-x

In [65]:
np.mean(x)

48.099489795918394

In [66]:
a=np.mean(df_xg.iloc[85:,0])  #predicted

In [67]:
a

86.95565663551798

In [68]:
b

NameError: name 'b' is not defined

In [ ]:
b=np.mean(df_xg.iloc[85:,-1]) #actual

In [ ]:
t=(a-b)/a

In [ ]:
t

### 2.) Decision Tree Model

In [ ]:
from sklearn.tree import DecisionTreeRegressor;
dtr_regressor=DecisionTreeRegressor(random_state=0);
dtr_regressor.fit(x_train,y_train);

### Error In Decision Tree Model

In [ ]:
dtr_pred=dtr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,dtr_pred)

### 3.) Random Forest Classification

In [ ]:
from sklearn.ensemble import RandomForestRegressor;
rfr_regressor=RandomForestRegressor(n_estimators=10,random_state=0);
rfr_regressor.fit(x_train,y_train);

In [ ]:
rfr_pred=rfr_regressor.predict(x_test)
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,rfr_pred)

In [ ]:
aqi_16.shape

In [ ]:
aqis=np.concatenate((aqi_15.reshape(365,1),aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1)),axis=1)
aqis

In [ ]:
xg_test=np.zeros((365,6));
for i in range(0,365,1):
    for j in range(0,5,1):
        xg_test[i][j]=aqis[i][j];

In [ ]:
xg_pred_2020=xg_regressor.predict(aqis)

In [ ]:
xg_pred

In [ ]:
aqis_2021=np.concatenate((aqi_16[[range(0,365)]].reshape(365,1),aqi_17.reshape(365,1),aqi_18.reshape(365,1),aqi_19.reshape(365,1),xg_pred_2020.reshape(365,1)),axis=1)

In [ ]:
xg_regressor.fit(x_train, np.ravel(y_train));

In [ ]:
fig1=plt.figure()
plt.plot(xg_pred_2020[range(0,183)])
plt.plot(aqi_20)
plt.legend(['prediction 2020','true 2020'])

In [ ]:
from sklearn.impute import SimpleImputer;
ds_imputer=SimpleImputer(missing_values=np.nan,strategy='mean');
ds_imputer.fit(aqis);
aqis=ds_imputer.transform(aqis);

In [ ]:
plt.plot(xg_regressor.predict(aqis_2021))
# plt.plot(dtr_regressor.predict(aqis))
plt.plot(regressor.predict(aqis[:,[1,2,3,4]]))
plt.legend(['prediction xg','prediction dtr','prediction svr'])