In [1]:
import pandas as pd;
import numpy as np;

In [2]:
ds_1=pd.read_csv('previous_3.csv');

In [5]:
X=ds_1.iloc[:,[1,2,3]].values;
Y=ds_1.iloc[:,-1].values;

In [6]:
X.shape

(1086, 3)

In [7]:
Y.shape

(1086,)

In [9]:
Y.reshape(1086,1)

array([[496.],
       [528.],
       [538.],
       ...,
       [420.],
       [484.],
       [509.]])

In [10]:
from sklearn.impute import SimpleImputer;
si = SimpleImputer(missing_values=np.nan , strategy='mean');
si.fit(X);
X=si.transform(X);

In [13]:
Y = si.fit_transform(Y.reshape(1086,1));

In [14]:
Y.shape

(1086, 1)

In [21]:
from sklearn.model_selection import train_test_split;
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1);

In [24]:
x_train.shape

(868, 3)

In [68]:
from sklearn.svm import SVR;
regressor = SVR(kernel = 'poly');
regressor.fit(x_train,y_train);

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [88]:
x_train.shape

(868, 3)

In [69]:
y_pred = regressor.predict(x_test);

In [70]:
y_pred.shape

(218,)

In [71]:
diff = np.ravel(y_test) - np.ravel(y_pred);

In [72]:
diff

array([ -36.23270873,  143.08902687,  -76.19616264,  -76.936638  ,
         50.7549725 ,    0.29806673,   -3.59332129,  -60.23700235,
          2.07063174,  -20.80301009,   93.17065016,  -20.54047597,
         45.67496149,   16.5758868 ,   41.53851192,  -24.86673339,
        178.37035815,   37.85594932, -118.72825252,    9.49435509,
        -47.58784143,  -14.01274482,   28.95912201,   -6.36942088,
         15.18427781,    7.17540169,  -30.62271025, -109.02163382,
        -13.12475325,   29.73364044,  -74.03243599,   -0.73185454,
         -4.27968394,  -26.50099252,  -68.60980992,   62.00497015,
        -19.1296784 ,  -30.73081084,   16.42014122,   -2.04017758,
        -28.29216124,   29.48945726,   -6.00717276,  -15.36364743,
          2.24198327,    8.0097027 ,   27.34543183,   19.00832874,
         68.03023591,  -80.25293019,   -2.6401012 ,   56.37516037,
          4.43158387,  -30.31355031,  -45.23172512,  -19.8654548 ,
          2.057439  ,  -24.23399167,   16.07984519, -138.00251

In [91]:
from xgboost import XGBRegressor;
regressor=XGBRegressor();
regressor.fit(x_train,y_train);

In [92]:
y_pred=regressor.predict(x_test);

In [93]:
y_pred

array([222.69705 , 201.34654 , 178.1717  , 337.1837  , 169.24852 ,
       298.27496 , 203.69366 , 267.1026  , 106.0645  , 324.18146 ,
       241.73193 , 266.611   , 246.37932 , 240.9555  , 367.9717  ,
       186.70361 , 290.2903  , 365.57285 , 307.85434 , 380.4232  ,
       250.47664 , 325.465   , 219.25313 , 349.818   , 206.6511  ,
       263.70505 , 308.23947 , 358.2307  , 317.33334 , 369.5731  ,
       355.9867  , 147.9002  , 281.30307 , 325.28943 , 317.55096 ,
       273.33017 , 205.72783 , 331.35095 ,  79.61912 , 327.0773  ,
       269.42053 , 265.2402  , 367.62366 , 335.83585 , 113.26945 ,
       138.60051 , 288.05762 , 281.63226 , 223.91684 , 258.1983  ,
       155.69153 , 222.67126 , 474.9234  , 375.11813 , 435.13217 ,
       422.4203  ,  82.54676 , 352.07062 , 277.0494  , 617.1265  ,
        97.722946, 307.73538 , 456.22702 , 214.46251 , 253.56604 ,
       110.972466, 166.56844 , 345.42453 , 233.29355 , 348.37082 ,
       342.1566  , 272.4736  , 259.3539  , 154.25008 , 321.421

In [94]:
diff_2=y_pred-y_test

In [95]:
diff_2

array([[  68.697052  ,   47.34654236,   24.17170715, ...,  272.21557617,
         -59.66457367,  155.61712646],
       [-118.302948  , -139.65345764, -162.82829285, ...,   85.21557617,
        -246.66457367,  -31.38287354],
       [ 114.697052  ,   93.34654236,   70.17170715, ...,  318.21557617,
         -13.66457367,  201.61712646],
       ...,
       [-181.302948  , -202.65345764, -225.82829285, ...,   22.21557617,
        -309.66457367,  -94.38287354],
       [ 132.697052  ,  111.34654236,   88.17170715, ...,  336.21557617,
           4.33542633,  219.61712646],
       [  -3.302948  ,  -24.65345764,  -47.82829285, ...,  200.21557617,
        -131.66457367,   83.61712646]])

In [46]:
per = (np.ravel(diff)/np.ravel(y_test)) * 100;

In [48]:
per.shape

(218,)

In [55]:
ans

31.201612295969934